### ISSUE TITLE
Timer: doesn't always appear in production, but ok in DuckPAN

### ISSUE THREAD

**Issue by mattr555** [duckduckgo/zeroclickinfo-spice#1389]
It probably has something to do with the `hidden` attribute setting [here](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/timer/timer.js#L16), as the html is loaded, but the hidden attribute is set:

![screenshot - 01012015 - 10 28 44 pm](https://cloud.githubusercontent.com/assets/4411471/5594063/95417748-9205-11e4-8344-8b9f723138ca.png)

This appears to be a race condition, as it works sometimes (notably on refresh). I'm not convinced the flash of unstyled content is really a bug...
cc @jagtalon @kethinov

**Comment by kethinov** [comment]
Looks like the JS (https://duckduckgo.com/share/spice/timer/1078/timer.spice.js) is loading prior to the CSS (https://duckduckgo.com/share/spice/timer/1078/timer.css), which isn't the case in DuckPAN.

Due to that, [the line you noted](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/timer/timer.js#L16) never executes because the element the `load` event is supposed to attach to isn't yet present in the DOM.

I just submitted a fix here: https://github.com/duckduckgo/zeroclickinfo-spice/pull/1390
