### ISSUE TITLE
Image IA vs Bitcoin address IA - Triggering

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/zeroclickinfo-spice#1534]
The DDG [Images IA](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Images.pm) is triggered a search of any Bitcoin address. This overtakes the [Bitcoin address IA](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/BitcoinAddress.pm). 

This is most likely a race condition, through testing it appears if the Bitcoin address IA returns a result before the Image IA loads then it is activated. However **the images IA shouldn't be triggering at all for a Bitcoin address.** (Unless it's relevant) 

Example: https://duckduckgo.com/?q=16finvwByyGebySewHchiDwnV385dsg4WP

Images IA result: https://duckduckgo.com/i.js?q=16finvwByyGebySewHchiDwnV385dsg4WP&o=json

![selection_222](https://cloud.githubusercontent.com/assets/5282264/6201967/6e49aa48-b505-11e4-9732-00f5514d67f6.png)

**Comment by moollaza** [comment]
@MrChrisW thanks for pointing this out. I'm no longer getting a result from the Bitcoin Addresss Spice but in either case, images shouldn't be triggering for that kind of query!

**Comment by MrChrisW** [comment]
@moollaza Can you double check, sometimes it takes a while to load... 4.3s

The API does return a [result](https://duckduckgo.com/js/spice/bitcoin_address/16finvwByyGebySewHchiDwnV385dsg4WP)

![selection_232](https://cloud.githubusercontent.com/assets/5282264/6214065/da3f8a34-b630-11e4-91f9-d66dfed3d17f.png)

**Comment by tommytommytommy** [comment]
@MrChrisW Your debugging is fantastic. Thanks for bringing this up. What's happening is that we first open a placeholder for the BitCoin IA and then wait for the upstream response. But, if the response takes somewhere on the order of more than three seconds, we assume that something awry has occurred upstream. To recover, because we've already displayed a placeholder, we use the next best IA that has content. But, as a last resort, if we have no other IA to show, we try to fill the placeholder using images. For this particular query, as there really are no images to show, the frowny face popped up instead.

As the bitcoin response here took ~4.5 seconds, the images/frowny face is the expected behavior. I'm not quite sure if there is a good way to address the long upstream response time without severely affecting all of our other IAs...

**Comment by MrChrisW** [comment]
@tommytommytommy Thanks for your explanation! That makes sense. 
Is there any reason we can't remove the placeholder if the image IA has been used as a failback and there's no results? Guessing this may be difficult to determine that the image IA has been called after the others have failed.

**Comment by tommytommytommy** [comment]
@MrChrisW We just bumped up the timeout for this particular IA to 5 seconds, and hopefully that should improve most bitcoin searches. Regarding the placeholder behavior, removing the placeholder after showing it is somewhat visually jarring, especially if there are many organic results below, so we actually prefer to not remove the placeholder once it's opened. Thanks again for your help :)
