### ISSUE TITLE
Snow: Impove snowflake effect

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1562]
http://php.quicoto.com/snow-html-canvas/, Demo: http://php.quicoto.com/examples/27/

This is more of the effect we'd like to see (simplified snowflakes, smaller).

Also, let's try 700 particles and update the background colour of the IA to `#D0D0D0`

https://duck.co/ia/view/snow

**Comment by jagtalon** [comment]
:+1: the snow oscillates pretty quickly as well. http://cl.ly/0J1J1K012L0v. Almost as if the snow flakes are shivering.

**Comment by gokul1794** [comment]
Is anyone working on this?

**Comment by moollaza** [comment]
@gokul1794 nope :+1:

**Comment by gokul1794** [comment]
I get this, so how do I test what I do?
API key not found. Using DuckDuckGo's endpoint:                                                                                            
"https://ddh1.duckduckgo.com/js/spice/snow/Phoenixville%2CPennsylvania%2CUnited%20States"                                                  
"500 Can't connect to ddh1.duckduckgo.com:443 (Connection refused)"

**Comment by MrChrisW** [comment]
@gokul1794 The issue here is that the API_KEY doesn't exist an an `env` var on your system so the faillback API is used, in this case `ddh1.duckduckgo.com` I've experienced a similar issue with DuckPan failing back to the `ddh1` endpoint which is currently not active, @moollaza fix?

The workaround is to plug `https://duckduckgo.com/js/spice/snow/$1` into the `spice to` value on [line 20 Snow.pm](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Snow.pm#L20) for testing purposes only.

**Comment by gokul1794** [comment]
Thanks @MrChrisW. That seems to work!

**Comment by gokul1794** [comment]
` var snowContainer = document.querySelector('.zci-wrap');`
I changed the class to be called to .zci-wrap and added <br>
```
.zci-wrap{
    height: 150px;
}
``` 
for testing purposes, not too sure why it isn't working :/

**Comment by gokul1794** [comment]
@moollaza `document.querySelector('.zci.zci--snow.is-active)` returns null. This is where we want the snowflakes to be shown right?

**Comment by gokul1794** [comment]
Ok i got this to work, Will make a PR soon :)
