### ISSUE TITLE
Color Picker: Initial look has the fields left blank on IE 8

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1598]
![screen shot 2015-03-06 at 11 23 01 am](https://cloud.githubusercontent.com/assets/81969/6528933/66b368f8-c3f3-11e4-92b4-deb6c9d262b8.png)

https://duck.co/ia/view/color_picker

**Comment by mattr555** [comment]
Are we still attempting to support IE8? We may want to go the way !g went [nearly 2.5 years ago](http://www.computerworld.com/article/2492571/web-apps/google-to-drop-support-for-ie8-on-nov--15.html). We could do what we're doing with IE7 and redirect to /html, or perhaps offer an alternative and link to [browse happy](http://browsehappy.com/).

I just feel pretty constrained trying to support it, and it seems that the experience isn't the same outside of IAs too:

![screenshot - 03062015 - 05 17 06 pm](https://cloud.githubusercontent.com/assets/4411471/6537444/c8c575be-c424-11e4-9402-8fbdc59959ae.png)
![screenshot - 03062015 - 05 18 42 pm](https://cloud.githubusercontent.com/assets/4411471/6537449/daf65816-c424-11e4-9c7d-34f4db81d195.png)

+ tour carousel broken
+ line height on query box off
+ arrow to select IA broken
+ no availability of border-radius

I feel like this comes up every month or so. I think it makes sense to have a better and more polished overall experience for the user on /html rather than a slowly deteriorating experience on the main site.

---
/rant. Sorry for sticking my thoughts here, but I think it's a consideration that should be discussed by the team sooner rather than later.

**Comment by jagtalon** [comment]
@mattr555 I forget the reason, but I do agree that it's a pain to support. I think it's because corporate environments still use it. I'll get back to you on that.

**Comment by MrChrisW** [comment]
Just wanted to weight in on this discussion.  

Sadly **IE8** still makes up nearly **10-19%** of the browser market share in 2015 (depending on who you talk to :smiley: )  I'd say this is the main reason DDG is still attempting to support it IMO. 

We may want to await the [Jan. 12, 2016](http://blogs.msdn.com/b/ie/archive/2014/08/07/stay-up-to-date-with-internet-explorer.aspx) deadline when MS offically drops support for the browser.

**Comment by mattr555** [comment]
@jagtalon @MrChrisW Thanks for the explanation. I checked with my dad, and it turns out that his corporate environment uses IE8. He told me about how Microsoft made a web client for Outlook and they suggest that they use Chrome to access it! I also had him access DDG from his native machine, and it looks like the screencaps from BrowserStack make it look worse than it is (but still not as great as a modern browser).

I think I was just having one of the typical "I hate IE" rants every web dev has at one point :). It really [does depend on who you ask](http://www.theie8countdown.com/).

As for the issue at hand, I'm not really sure what the problem is. Do IE's dev tools give any insight?

**Comment by MrChrisW** [comment]
@mattr555 If I had a dollar for every time I cursed IE I'd be rich :laughing: 

I believe the reason it looks worse when you've viewed it in BrowserStack is you're most likley viewing the DuckPAN version which degrades in IE. However it looks better in production. 

I've done a little bit of debugging and narrowed the first issue down to adding the [event listeners](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/color_picker/color_picker.js#L683-L689) to the local dom objects. IE 8 throws `Object doesn't support this property or method`. 

After a little research it looks like IE8 doesn't support `addEventListener` instead `attachEvent` needs to be used: http://stackoverflow.com/questions/9769868/addeventlistener-not-working-in-ie8

![selection_259](https://cloud.githubusercontent.com/assets/5282264/6539990/6498a2de-c4c2-11e4-9ef9-540f797b4a89.png)

**Comment by moollaza** [comment]
@MrChrisW @mattr555 this seems like a more jQuery-esque fix: http://stackoverflow.com/questions/9389968/jquery-touchstart-in-browser#9389999

Not sure if either method is better...

**Comment by moollaza** [comment]
IE 8 no longer supported...
