### ISSUE TITLE
Time: Broken queries 

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/zeroclickinfo-spice#1730]
Looks like the PR:  #1661 broke a few queries for the Time IA. 

Examples: 
- https://duckduckgo.com/?q=time+North+Dakota - **Fixed**
- https://duckduckgo.com/?q=time+New+York

I've tested reverting back to before PR #1661 and can confirm the above queries work.
---

IA Page:  http://duck.co/ia/view/time

**Comment by MrChrisW** [comment]
CC// @jdorweiler @moollaza

**Comment by jdorweiler** [comment]
Thanks @MrChrisW.  I'll take a look at it.

**Comment by tagawa** [comment]
Further examples <a href="https://duck.co/forum/thread/13061/time-queries-not-working">from the forum</a>, showing there's some inconsistency in the triggering:

* https://duckduckgo.com/?q=time+Paris (does trigger)
* https://duckduckgo.com/?q=time+London (doesn't trigger)
* https://duckduckgo.com/?q=time+in+London (does trigger)
* https://duckduckgo.com/?q=time+in+Manila (doesn't trigger)

**Comment by moollaza** [comment]
Seems to be a caching issue going on here... I've made a task for the team. These queries work as expected in DuckPAN. I was able to get results for all of these before:

![2015-04-20_13h47_31](https://cloud.githubusercontent.com/assets/873785/7236625/f27f3bbc-e763-11e4-8a54-34a3a174acec.png)
![2015-04-20_13h47_45](https://cloud.githubusercontent.com/assets/873785/7236624/f27db68e-e763-11e4-8670-c9d3d2e9b3eb.png)

**Comment by altern8tif** [comment]
Still trying to figure out why `time in new york` doesn't trigger the IA, even in DuckPAN.

@moollaza Any updates on this?

**Comment by moollaza** [comment]
@altern8tif it does trigger in prodution, but it's failing the relevancy check because we're triggering this using our internal "Deep" method. It's determining the location as "new york, new york" which when compared against our relevancy check, fails.

It doesn't trigger in DuckPAN because "New York" isn't in the Capitals.yml file that it uses. We could adjust that file to include other big cities which would help I think

**Comment by MrChrisW** [comment]
Looks like these queries have been fix:
+ https://duckduckgo.com/?q=time+London (doesn't trigger)
+ https://duckduckgo.com/?q=time+in+Manila (doesn't trigger)

>It's determining the location as "new york, new york" which when compared against our relevancy check, fails.

@moollaza Anyway to tweak the relevancy checking in this case to avoid a fail?

@altern8tif @tagawa I'd be interested to see if there are any other queries that fail

**Comment by moollaza** [comment]
>@moollaza Anyway to tweak the relevancy checking in this case to avoid a fail?

@MrChrisW there are some ways, but the best solutions I've thought of require some internal changes. 

An interim "solution" is to hard code these queries to skip relevancy checks, seeing as they're fairly popular.

**Comment by MrChrisW** [comment]
Other quires that don't trigger 

Gurgaon
Hobart
New York
Manila

Reported #2083 & #2353

**Comment by gitaarik** [comment]
It looks like most US cities I try don't work. How can this issue still be open for so long? Is it a hard problem?

**Comment by mrshu** [comment]
Hey everyone,

Sorry that it took this long, but this should generally be fixed now.

The gist of the issue was as follows: the API responds with "United States" as the country for US-based queries and we were comparing it to "USA", which was grabbed from the title of the `timeanddate.com` website. This was fixed internally and virtually all of the issues described in this task (except for `time in Gurgaon` -- that is still somewhat broken but being taken care of) should be fixed now.

I am not sure what should happen with this issue now, but I let the maintainer figure that out =).

Once again, sorry that it took this long. I firmly believe that it should not (and will not) in the future).
