### ISSUE TITLE
RxInfo: Relevancy Check Suppresses Some Results

### ISSUE THREAD

**Issue by medicosconsultants** [duckduckgo/zeroclickinfo-spice#1756]
The [relevancy checking](https://github.com/duckduckgo/zeroclickinfo-spice/commit/671749c87fad7c96dbba7321442e6eba3284d63e) added to RxInfo seems to be blocking some valid instant answer results.

For example: the queries "[pill 00093-7155-98](https://duckduckgo.com/?q=pill+00093-7155-98&ia=rxinfo)" and "[pill 93 7155](https://duckduckgo.com/?q=pill+93+7155&ia=rxinfo)" work fine and trigger the RxInfo instant answer.

However, "[pill 0093-7155-98](https://duckduckgo.com/?q=pill+0093-7155-98&ia=answer)" (FDA format national drug code) doesn't trigger the instant answer, even though it returns a [valid response from the API](http://rximage.nlm.nih.gov/api/rximage/1/rxnav?parse=0093-7155-98). Neither does "[pill tv](https://duckduckgo.com/?q=pill+tv)" (imprint match), which also has a [valid API response](http://rximage.nlm.nih.gov/api/rximage/1/rxnav?parse=tv). And the same goes for, "[pill pfizer 225](https://duckduckgo.com/?q=pill+pfizer+225)" (multiple imprint), and it too returns a [valid response from the API](http://rximage.nlm.nih.gov/api/rximage/1/rxnav?parse=pill%20pfizer%20225).

------ 

IA Page:  https://duck.co/ia/view/rx_info

**Comment by MrChrisW** [comment]
Thanks for reporting @medicosconsultants, sorry to partially break your IA :wink: 

@moollaza Is this related to the relevancy, skipped words bug mentioned in [#1750](https://github.com/duckduckgo/zeroclickinfo-spice/pull/1750#issuecomment-92426959) ?

**Comment by moollaza** [comment]
@medicosconsultants @MrChrisW the `00093` vs `0093` fails because we're comparing `0093` against `0009` and they're not the same, so the relevancy test fails.

@medicosconsultants is there a standard number of preceding 0's? Could we always change 2 leading zeros into 3? So when we see 0093, it becomes 00093?

As well, could the imprint for the pill be passed along through the API? We need something to compare against the query to make sure it's relevant. We were getting too many false-positives so we had to reign in the triggering for this.

**Comment by MrChrisW** [comment]
@medicosconsultants Have you had time to address the above questions?

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/) and because this has gone stale. We are now only accepting issues for essential bugs/fixes.
