### ISSUE TITLE
MetaCPAN: More at link broken for certain queries

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1815]
https://duckduckgo.com/?q=CPAN%3A%3ARepository+cpanm&ia=software

Looks like this IA could also use a couple visual updates...we should probably have a Title and Subtitle and display any extra useful information.

Now that we have the `list` group, this additional rows will be suppressed initially so we can show more data now, without taking up too much space!

**Comment by digital-carver** [comment]
By the way, another pain point I came across in the MetaCPAN IA is that the module name has to be in exact case. For eg. `lwp::useragent` or `LWP::Useragent` doesn't work, it has to be exactly `LWP::UserAgent` in the query. Otherwise the IA doesn't appear at all, which quite confused me until I realized it was about case-sensitivity. 

Does the MetaCPAN API provide a way to make case insensitivity work? ElasticSearch is quite beyond me, but some ddg-ing tells me the `"analyzer" : "lowercase"` in http://api.metacpan.org/v0/module/_mapping might be used in some complex incantation to achieve this. 

It first seemed like [/search/autocomplete](https://github.com/CPAN-API/metacpan-examples/blob/master/scripts/endpoints/search/autocomplete/www-mech.pl) might be the answer; and it does work for, say, [lwp::useragent](http://api.metacpan.org/v0/search/autocomplete/?q=lwp::useragent&size=1&fields=name,author,description,version,distribution,abstract), but fails with others like [Tk](http://api.metacpan.org/v0/search/autocomplete/?q=tk&size=1&fields=name,author,description,version,distribution,abstract).
