### ISSUE TITLE
"what's the time in" often shows weather

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/zeroclickinfo-spice#1821]
https://duckduckgo.com/?q=what's+the+time+in+philadelphia  
https://duckduckgo.com/?q=what's+the+time+in+paris%2Cfrance

**Usually shown when there's no space after city-level comma (as in the france example) 
![screen shot 2015-05-02 at 2 38 00 pm](https://cloud.githubusercontent.com/assets/1846953/7442285/ea6ea9ca-f0d8-11e4-834a-473734725a64.png)

----

IA Page: https://duck.co/ia/view/time

**Comment by mr-karan** [comment]
Just noticed the difference. If you use what's then weather shows, otherwise if you use whats then time is displayed

![firefox_screenshot_2015-05-02t07-59-45 025z](https://cloud.githubusercontent.com/assets/5689132/7442900/d4ead6c2-f142-11e4-8069-102f7ec2d901.png)
![firefox_screenshot_2015-05-02t21-44-42 118z](https://cloud.githubusercontent.com/assets/5689132/7442901/d4f069c0-f142-11e4-85d0-645095c2cdbb.png)

**Comment by moollaza** [comment]
hmm interestingly this query doesn't seem to trigger the IA the usual way --- it seems to be triggering internally because the query "time in india" doesn't seem to trigger this in DuckPAN...

I'll be sure to investigate this!

**Comment by jagtalon** [comment]
Can't reproduce anymore. Seems to be working.
