### ISSUE TITLE
Currency: "$500 to kr" doesn't work but "$500 to dkk" does

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1846]
Symbols such as "kr" should work as well. See https://github.com/duckduckgo/zeroclickinfo-spice/pull/1823#issuecomment-102351566

------ 

IA Page: https://duck.co/ia/view/currency

**Comment by javathunderman** [comment]
Should this and #1847 be the same issue?

**Comment by larseng** [comment]
Norwegian kroner (NOK) and swedish kroner (SEK) also uses kr, so should kr automatically be danish kroner (DKK)?

**Comment by yuwash** [comment]
According to the [2013 BIS triennial central bank survey](http://www.bis.org/publ/rpfx13fx.pdf) (p. 12) SEK has consistently been the most traded of the three with 1.8 % daily global forex market turnover share in 2013, whereas 1.4 % for NOK and 0.8 % for DKK. The order has remained constant in every triennial figure since 1998. So if we choose a default for kr, SEK might be the most popular choice.

**Comment by edgesince84** [comment]
@yuwash thanks for the stats!

**Comment by CatQuest** [comment]
as a Norwegian, I would expect "NOK" for "kr". would it possibly be prudent to just how all 3 of them? ie. write "$500 to kr" will give 500 USD = 3,398.18 DKK = 4,147.87 NOK = 4,516.18 SEK
remember also that "dollar" can also mean Australia (AUD) and Canadian (CAD) dollar. assuming one of these with simply "D" would be unquestionably wrong too,.

**Comment by pjhampton** [comment]
This has now been solved 👍

**Comment by yuwash** [comment]
For `500 kr to USD` I get the right thing (kr being SEK), but `500 USD to kr` still does 500 **SEK to USD**, unlike `500 USD to SEK` or `$500 to SEK` which works fine (get 4145.95 SEK). For some reason `$500 to kr` shows 4034.13 NOK. A compromise for @CatQuest :laughing: ?
