### ISSUE TITLE
Airlines instant answer gives results from previous, not current, day

### ISSUE THREAD

**Issue by danieljruben** [duckduckgo/zeroclickinfo-spice#1879]
http://duck.co/ia/view/airlines

Expected behavior: using Airlines instant answer gives flight information for a given flight on *current* day.

Actual behavior: using Airlines instant answer gives flight information for a given flight for the *previous* day.

Example search URL: https://duckduckgo.com/?q=vx+412&t=osx&ia=airlines

Searched 2015-06-01 09:45, gives following result:
![screen shot 2015-06-01 at 09 46 39](https://cloud.githubusercontent.com/assets/823922/7914144/27bcf18e-0843-11e5-89a0-f25922bb6bfd.png)

OS: OS X 10 Yosemite v10.10.3
Browser: Safari v8.0.6

Same problem occurred when searching on iPad Mini running iOS 8.3 yesterday evening.

**Comment by moollaza** [comment]
@danieljruben thanks a lot for reporting. Looking at the API response it's only giving us information for this flight.

You're totally right that there's another ongoing flight which departed today.

![virgin_america_flight_412_-_google_search](https://cloud.githubusercontent.com/assets/873785/7928119/b901f278-08b8-11e5-8556-1c7fc74442e7.png)

It looks like we're using the API endpoint to search for flights that *arrive* on the current day -- we should probably look for flights that departed today, and fallback to arrivals.

**Comment by whmountains** [comment]
I'm not sure if it would work in all cases to search for flights departing today and only fall back to flights arriving today if no flights are found.  Many flights are sometimes grouped under the same flight number and this would create an edge case one of those flights is a flight that left on the previous day but arrived on the current day.

I just ran into a flight that would have triggered this edge case.

![duckduckgo_flight_error](https://cloud.githubusercontent.com/assets/8680147/8530844/6ae26e34-23d8-11e5-91e4-d56f172b29e1.jpg)

If I'm waiting for a friend who is coming in on this flight and I look up their flight info some time after midnight I wouldn't see the flight because the instant answer would never "fall back" to searching by arrival time because the search by departure time would have found flights.

Admittedly, in this case there is only a 14 minute time frame in which this error could occur before the flight had landed but it's still a bug.  Also, there probably exist other flights that have a longer time frame.  (for example, a flight that leaves at 11:45 and arrives at 4:00 AM)

The flight tracker API doesn't seem to have an option to look up flights arriving *or* departing today in a single query so the only option would probably be to do both queries and merge them into one list while throwing out the duplicates.  Am I thinking correctly?

**Comment by moollaza** [comment]
>so the only option would probably be to do both queries and merge them into one list while throwing out the duplicates. Am I thinking correctly?

Your thinking is exactly correct and we've recently implemented exactly that functionality. We'll be tweaking it in the coming weeks but for now we should have a better look into flights arriving/departing for a 24-hour window.

**Comment by moollaza** [comment]
Closing as this should now be be resolved.
