### ISSUE TITLE
Scratchpad: Unable to use backspace 

### ISSUE THREAD

**Issue by Manouchehri** [duckduckgo/zeroclickinfo-spice#1894]
On Firefox for Android, I'm able to type, but the backspace button is non-functional with the soft keyboard (I have not tried a wired one yet).

Sample URL: https://duckduckgo.com/?q=JavaScript+scratchpad

**Comment by moollaza** [comment]
Hi @Manouchehri, the editor should be disabled for Mobile devices now. It was originally intended to because of the issue you've pointed out but the code was old and didn't work anymore. I updated the code this evening and we pushed it live.

Please let me know if the editor is still appearing for you on mobile!

**Comment by Manouchehri** [comment]
@moollaza Scratchpad is now gone for Firefox Android, looks good to me.

**Comment by moollaza** [comment]
@Manouchehri thanks :+1:
