### ISSUE TITLE
Airlines: flight tracker simultaneously displays flight status as "landed" for all phases of a multi-stop flight.

### ISSUE THREAD

**Issue by whmountains** [duckduckgo/zeroclickinfo-spice#1967]
The flight tracker instant answer doesn't calculate the flight status separately for each phase of a multi-stop flight.  For example, when I look up United 6486 (a two-segment flight) it shows that both segments are "landed".  That just doesn't make sense.    A flight can't be landed at two airports at once.

![ua6486_at_duckduckgo](https://cloud.githubusercontent.com/assets/8680147/8398567/878d5d00-1dca-11e5-9ece-02047868b8e2.jpg)

------
IA Page:  http://duck.co/ia/view/airlines

**Comment by iambibhas** [comment]
It didn't land at both airport at the same time. It landed on the first airport at 6:06PM and on the second airport on 7:50PM.

**Comment by whmountains** [comment]
In that case shouldn’t it have said “departed”, or something else 
like that for the first airport?

**Comment by iambibhas** [comment]
@whmountains both are different routes, they are just connecting flights. For people who travelled CPR to DEN, the first one was the entire journey. For people travelling from DEN to GJT, second one was the entire journey.
(I'm talking from my knowledge of airlines in India. Connecting flights are just 2 different journeys. It's a connecting flight for people travelling from CPR to GJT. But people also get off and get in the flight in DEN. I'm not entirely sure if that's the same case in USA.)

Either way, the first one can't be `departed` because the flight was from CPR to DEN and it has indeen made the journey and landed. The second flight will be at the state Departed/Landed from that point on.

**Comment by whmountains** [comment]
That makes sense.  In other words, the `departed`/`landed` status 
message applies to a flight, not to the location of the plane relative 
to the airport.  A plane could make hundreds of flights and they would 
all be landed even though the plane was not at any of those airports.
