### ISSUE TITLE
Gifs: Still Images instead of Gifs

### ISSUE THREAD

**Issue by altern8tif** [duckduckgo/zeroclickinfo-spice#1990]
IA shows still images rather than gifs.  Is that a bug or does the Giphy API not allow (moving) gifs to be shown?

------
IA Page:  http://duck.co/ia/view/gifs

**Comment by jagtalon** [comment]
@altern8tif we went with showing still images instead of gifs because gifs are MASSIVE! They can eat up a lot of bandwidth and slow down your experience on DDG. I'd like it to move as well, but no immediate solutions in sight.

Best compromise is to probably load the gif when we hover like in Giphy. CC @bsstoner @sdougbrown just so that this is in your radar. Do you have any other comments on this issue?

**Comment by altern8tif** [comment]
@jagtalon Yea I thought it might have been a performance-related issue.  

I wouldn't mind working on this IA to add the *load gif on hover* functionality though.  Should I go ahead?

**Comment by moollaza** [comment]
@altern8tif I think that should be possible. If you wouldn't mind developing it as an experiment I'm sure the frontent team would appreciate playing around with it to see how it work and if it's something we should integrate at a deeper level

**Comment by jagtalon** [comment]
@altern8tif Give it a shot!

**Comment by edgesince84** [comment]
this was addressed by https://github.com/duckduckgo/zeroclickinfo-spice/pull/2154 already.  thanks!
