### ISSUE TITLE
Whois does not trigger for zomato.com

### ISSUE THREAD

**Issue by gokul1794** [duckduckgo/zeroclickinfo-spice#1992]
Not sure why it isn't working for this, however it works on the whois site. Also why is it that sometimes preference is given to images over the IA?
![whoisnotworking](https://cloud.githubusercontent.com/assets/6311809/8503166/6ed05cf6-21d8-11e5-89ce-d2fe6b42c6c6.png)

________
https://duck.co/ia/view/whois

**Comment by kbhat95** [comment]
@gokul1794 works for me.

**Comment by gokul1794** [comment]
Funny, it works for me now. However this doesn't now, any idea why something like this happens?
![xxx](https://cloud.githubusercontent.com/assets/6311809/8510578/faecb014-230d-11e5-90b5-5705c48de0b8.png)

**Comment by MrChrisW** [comment]
@kbhat95 @gokul1794 Looks like the [query](https://duckduckgo.com/?q=whois+zomato.com&ia=whois)

>Funny, it works for me now. However this doesn't now, any idea why something like this happens?
@gokul1794 Thanks for reporting this

I've investigated a little.

This works fine on DuckPAN, the IA triggers for the query [`whois zomato.xxx`](https://gist.githubusercontent.com/MrChrisW/5579db2f3f269ade3f24/raw/a6aef2ad9212105c3962ccde3a87b36ae11470d2/gistfile1.sh) and returns a result. The API is returning a correct result https://duckduckgo.com/js/spice/whois/zomato.xxx

![selection_002](https://cloud.githubusercontent.com/assets/5282264/8522450/d61a657e-2420-11e5-8181-30f91848753d.png)

___

I think the reason a result isn't being returned is due to the search query being deemed unsafe by DDG (explicit). Looks like this automatically disables Spice IA's?  - @moollaza can you confirm?

*Good example of this can be demonstrated using the following queries:*
![image](https://cloud.githubusercontent.com/assets/5282264/8522412/653fa904-2420-11e5-951d-07eee3868ac5.png)
[whois shit.com](https://duckduckgo.com/?q=whois+shit.com) - **no IA Whois loaded**
[whois shit.com](https://duckduckgo.com/?q=whois+good.com) - **loads Whois IA**

**Comment by gokul1794** [comment]
@MrChrisW Ahh, I see. Do you know why the images are given preference over the IA sometimes?

**Comment by moollaza** [comment]
>the search query being deemed unsafe by DDG (explicit). Looks like this automatically disables Spice IA's? - @moollaza can you confirm?

@MrChrisW @gokul1794 thanks for reporting! This is definitely a bug. We should still be triggering IA's even when adult terms are detected but it looks like right now we're not.

I've made a task for the team to investigate.

>Ahh, I see. Do you know why the images are given preference over the IA sometimes?

@gokul1794 this mostly depends on the speed of the IA and if we have a signal that images might relevant to show. If the Spice is taking too long, we'll show Images, and then add the IA tab to the metabar when it's ready.

**Comment by tommytommytommy** [comment]
I've submitted a fix for this and it should be rolling out with the next release. Thanks for the catch! Will post an update after the release goes out.

**Comment by MrChrisW** [comment]
@tommytommytommy :+1:

**Comment by gokul1794** [comment]
@tommytommytommy :+1:

**Comment by tommytommytommy** [comment]
![screen shot 2015-07-24 at 2 47 22 am](https://cloud.githubusercontent.com/assets/5326740/8869144/6f464048-31ae-11e5-99dc-3acf8a8525ac.png)

Hurray! @gokul1794 & @MrChrisW thanks for reporting the bug and the tremendous debugging help!

**Comment by tommytommytommy** [comment]
One more for good measure, as this was the actual broken query:

![screen shot 2015-07-24 at 2 52 13 am](https://cloud.githubusercontent.com/assets/5326740/8869196/1589603e-31af-11e5-82cb-20fdd63b5c1d.png)

**Comment by gokul1794** [comment]
@tommytommytommy Too good :ok_hand:
