### ISSUE TITLE
IsItUp: Text displays poorly in Dark theme

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/zeroclickinfo-spice#2016]
Text displays pool in dark theme.
Vertical divider in footer displays poorly as well.

![screen shot 2015-07-08 at 11 26 41 am](https://cloud.githubusercontent.com/assets/7061920/8580062/40df5822-256d-11e5-8779-641252beeee7.png)

cc @moollaza @jagtalon 

------
IA Page:  http://duck.co/ia/view/is_it_up

**Comment by moollaza** [comment]
Looks like the template needs to specify the text colours using the new `tx-clr--{color}` CSS classes, rather than specifying any colors in the CSS.

The available classes can be found here: https://duckduckgo.com/styleguide#txt-n-color


> Vertical divider in footer displays poorly as well.

This is now fixed. We have a new credits link, which is positioned in the top-right corner.
