### ISSUE TITLE
Currency: The default currency should depend on the person's region

### ISSUE THREAD

**Issue by waghso** [duckduckgo/zeroclickinfo-spice#2045]
Hi,

I'm from India where Indian rupee(INR) is currency. When I search for $123 result shows 112.87 EUR.
This is unacceptable. I'm in India and and I only care about INR currency. This may be same for other users as well. Can you convert currency to according to Nation of user???

![image](https://cloud.githubusercontent.com/assets/6398904/8741686/48d99808-2c7a-11e5-93e3-a1ec617124b0.png)

------
IA Page:  http://duck.co/ia/view/currency

**Comment by gokul1794** [comment]
I think this IA should check if the user has given a region and convert to that or not trigger at all on a query like this if he hasn't!

**Comment by gokul1794** [comment]
I think this IA should check if the user has given a region and convert to that or not trigger at all on a query like this if he hasn't!

**Comment by jagtalon** [comment]
The https://duck.co/duckduckhack/language_and_location_apis API could help, and this actually might be the ideal behavior. Any comments on this @moollaza @chrismorast?

**Comment by jagtalon** [comment]
Or we could use the region instead by using `DDG.settings.get("kad")`

**Comment by MrChrisW** [comment]
@waghso Thanks for reporting this.

@jagtalon I'll jump on this issue. I think using the `$loc` var from the location API will be easiest solution.

However using JS to grab the set location may be more accurate. Quick question: does this use the same data to determine user location as the location API?

**Comment by jagtalon** [comment]
@MrChrisW it actually gets the data from the region settings so this one is set by the user. :)

**Comment by moollaza** [comment]
Just so everyone is aware, this IA is setup to automatically convert the input currency to the most common converted currency, for the given input currency IIRC. This way anyone who searches a USD amount will get EUR because that's the most common/popular conversion.

I think we might want to sit on this for a bit and see if we get any other complaints. So far no one else has complained and this is a pretty popular Instant Answer.

I'll discuss this further with the team to hear their thoughts.

**Comment by MrChrisW** [comment]
@moollaza :+1: Sounds fine! Happy Weekend btw.

**Comment by moollaza** [comment]
Hey guys, so I've discussed this with the team and we came to some conclusions. Ultimately I don't think we should default to the user's location because I feel the expectation is that it will use to most common one. However, there's no need for us to only show the single most popular conversion for the input currency.

We unanimously agreed that when no input is given, we should handle it the same way we handle it when the input is "1" unit or just the name of the currency, like "usd".

So if you search "$12 usd" we should show the tiles which contain the conversions to the most common. If the user really wants to know what the value of a given currency is in a specific currency its highly likely that they'll specify both the FROM and TO currencies.
