### ISSUE TITLE
Airlines: "Showing 2 Flight" Typo

### ISSUE THREAD

**Issue by hawkrives** [duckduckgo/zeroclickinfo-spice#2068]
When searching for a flight that happens once a day, at least (for instance, "DL 580"), the header area that describes how many results were found says "Showing 2 Flight"—that is, it's not pluralized properly.

I've spelunked around this repo a bit, but I'm not sure where the stuff for that header is located. I have confirmed that it does not happen with the Images tab, so it seems to be type-specific, but I can't seem to find where that's defined.

Anyway, I *love* DuckDuckGo, and being able to file issues like this is amazing!

------
IA Page:  http://duck.co/ia/view/airlines

**Comment by moollaza** [comment]
@hawkrives thanks a lot for reporting this!

The issue comes from here: https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/airlines/airlines.js#L275

We're using a new approach to gather flights from multiple API calls, and so the check is actually true because the API call we're considering only had 1 result. We're not taking into account the additional flight we grabbed in another call. We need to check the length of our finalized array to make sure it's correct.

Also we have a fancy new pluralization helper fn, that can be used here: `DDG.pluralize(num, 'single form', "plural form")`. When there's no plural form, we return `"single form" + "s"` when necessary.

**Comment by yash14123** [comment]
Is this fixed or still open?

**Comment by tagawa** [comment]
Thanks for the ping @theaverageguy. Looks like the wording on this has changed so this is no longer an issue: https://beta.duckduckgo.com/?q=ua78&iai=1&ia=flights
