### ISSUE TITLE
BrainyQuote: 

### ISSUE THREAD

**Issue by mohan08p** [duckduckgo/zeroclickinfo-spice#2126]
yes, its good,  but we can also add the sections regarding #430

**Comment by moollaza** [comment]
@mohan08p thanks for the input. I'm going to close this as it’s a duplicate of #409. If you'd like, I'd suggest you add a comment over there expressing your interest.

I'm not sure we can get topics to work though because we're using a custom API that brainy quote seems to have made for us. We'll likely need to contact them.
