### ISSUE TITLE
Currency: "1Ƀ" should be recognized also as 1 Bitcoin, 1Btc or 1XBT

### ISSUE THREAD

**Issue by xuv** [duckduckgo/zeroclickinfo-spice#2142]
Ƀ, the [bitcoin symbol](http://bitcoinsymbol.org/) is used by a growing part of the Bitcoin community. It certainly works better than the [฿](https://duckduckgo.com/?q=1%E0%B8%BF&ia=currency) which DDG, as expected, recognizes as the Thai Bath symbol.

Since you can type BTC, Bitcoin or XBT and they all get recognized as Bitcoin, seems fair to have the Ƀ. So far, searching for [1Ƀ in $](https://duckduckgo.com/?q=1%C9%83+in+%24) does not bring anything close to Bitcoin.

---

IA Page: https://duck.co/ia/view/currency

**Comment by moollaza** [comment]
This is a great idea, implementing it isn't simple though because we're using the `Currency_symbols` classifier in our regex to ensure we only match on what are symbols that represent "real" currencies.

Some tinkering will need to be done in order to get this working.

We also have the Cryptocurrency Instant Answer which is made for conversions between most crypto currencies. This trigger could also be used there

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
