### ISSUE TITLE
SoundCloud: Sorting by Date Posted?

### ISSUE THREAD

**Issue by JaegerBombastico** [duckduckgo/zeroclickinfo-spice#2168]
Not really a problem, but it would be a good idea if instead of it just randomly throwing up random songs from the soundcloud, if it could sort it all by date posted.

------
IA Page:  http://duck.co/ia/view/sound_cloud

**Comment by moollaza** [comment]
@JaegerBombastico the default ordering is actually based on the number of "Likes" the song has according to the API. We don't have it done yet, but we're working to bring filtering options to the UI which will not only show you the default sort, but let you select another sorting option (such as release date, for example) to re-order the results.

**Comment by moollaza** [comment]
I think for now popularity is probably the best way to sort results and so I'm marking this as tolerated. I totally agree that users should be able to change the sorting as they like, so hopefully once we have filtering, we can raise this issue again and have someone implement a sort-by-date filter.

**Comment by zekiel** [comment]
@jdan  do you want to revisit this or close it out? Not sure it's best suited as an issue.

**Comment by jdan** [comment]
@zekiel Probably best to close it out :) I'll have to get a new environment set up and everything.

**Comment by j3pic** [comment]
@moollaza This is not a tolerable bug. Popularity is the absolute *worst* sorting option. Everybody else likes garbage, and then it sticks to the top of the search results forever. The contents of a given tag never, ever change because the ones on top accumulate more likes, which solidifies their position on the list. 

The only way I could possibly get *good* results would be to write my own spider. But you require JavaScript to even see the tracks. So that means I'd have to use Selenium! >:(

Why does it take over a year and a half to parameterize an `ORDER BY` clause in an SQL query?

The only reason I'm sticking around here is because MixCloud doesn't even let you skip within tracks, and neither do any of the SoundCloud alternatives out there (though they DO let you sort the results). Why do all music sites suck so hard?

**Comment by wacko37** [comment]
Lol..... "Why do all music sites suck so hard"

I totally agree here!!! Soundcloud has so much potential to be something so great, like far beyond Spotify and the rest. But instead it's let down by the simplest of things, that are so simple it makes using them unbearable.

**Comment by moollaza** [comment]
Locking this thread. This Instant Answer has been offline for some time and isn't expected to come back.
