### ISSUE TITLE
Airlines: Relax triggering (update regexs)

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#217]
Flight info doesn't come up with the query "Lufthansa LH 426".
https://duckduckgo.com/?q=Lufthansa+LH+426

**Comment by javathunderman** [comment]
@moollaza What we would have to fix here?

**Comment by moollaza** [comment]
@javathunderman it looks like the `handle` needs to be updated to account for these different query formats. I don't think it was written to expect the airline, airline code and the flight number in the query. It should be relaxed to accept them and combos of them.

**Comment by MrChrisW** [comment]
Closing - All queries mentioned now work, assuming due to internal triggering changes.

+ https://duckduckgo.com/?q=426+LH&ia=flights
+ https://duckduckgo.com/?q=LH+426&ia=flights
+ https://duckduckgo.com/?q=Lufthansa+LH+426&ia=flights

Please re-open if any additional flight queries are non functioning.
