### ISSUE TITLE
SoundCloud: No Volume Control or Skip Ahead.

### ISSUE THREAD

**Issue by HarshInvader** [duckduckgo/zeroclickinfo-spice#2298]
@jdan 
Having online a play-pause feature might not be enough. I many-a-times had the urge to move ahead in the song but when I tried click on the circle ahead, it paused. 
And Volume Control won't be that difficult, c'mon!

---

IA Page:  http://duck.co/ia/view/sound_cloud

**Comment by gpestana** [comment]
Play, pause, skip and volume would be nice features to add. SoundCloud provides those features through their API (https://developers.soundcloud.com/docs/api/html5-widget). I will try to implement these features.

**Comment by MrChrisW** [comment]
Thanks for the suggestion @HarshInvader 

@gpestana Please reach out to any of the DuckDuckGo community members for assistance or shot an email off to `open@duckduckgo.com`

**Comment by gpestana** [comment]
@MrChrisW yep, just got help from @moollaza on Slack!

I dug a bit into this issue and these are my conclusions:

1. We cannot use Sound Cloud's API because it is exposed through their widget thas has to be embedded somehow. This might pose privacy issues (thanks @moollaza for the heads up on this issue);
2. Sound Cloud's IA is rendered with [audio_item.handlebars](https://github.com/duckduckgo/duckduckgo-answerbar-templates/blob/master/item/audio_item.handlebars), so I guess that at least pause, stop and skip can be implemented in the audio player. Though, I can't find where the player's JS code is. Maybe it's not open sourced?
3. Based on the player's code, maybe the volume controller can be added.

Any suggestions on how we could do this? I believe it can be done and since the [audio_item.handlebars](https://github.com/duckduckgo/duckduckgo-answerbar-templates/blob/master/item/audio_item.handlebars) template is used in more IAs (and potentially can be used further in many others), it would be a good time investment to have a nice and fully featured audio player to use on DuckDuckGo :)

**Comment by moollaza** [comment]
As @gpestana has mentioned, this functionality isn't currently possible without us doing some internal work to expose the audio player's volume and tracking capabilities to the templates, and then updating the templates to allow for this.

@abeyang @bsstoner what are your thoughts on this?

I like the suggestion but I don't think this is something critical. If it's a simple fix it might be nice to have though?

**Comment by rasikapohankar** [comment]
Helloo! I was wondering if it might also be possible to add a 'Repeat Song' button? Would be great to have this control!

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
