### ISSUE TITLE
Maps: Query does not trigger IA

### ISSUE THREAD

**Issue by kandyjet** [duckduckgo/zeroclickinfo-spice#2320]
Hi folks,

khorfakkan map

https://duckduckgo.com/?q=Khor+Fakkan+map
https://duckduckgo.com/?q=khorfakkan+map

Google shows the map while duck does not :(

---

IA Page:  http://duck.co/ia/view/maps_maps

**Comment by moollaza** [comment]
@kandyjet thanks for reporting this!

I'll have the team investigate this internally...

**Comment by kandyjet** [comment]
your welcome :)

**Comment by telekommander** [comment]
Same here:
It is different if you search for `Prellerstraße 14, Dresden`   (_German Umlauts_)
https://duckduckgo.com/?q=Prellerstraße+14%2C+Dresden
instead of `Prellerstr 14, Dresden` or `Prellerstrasse 14, Dresden`
https://duckduckgo.com/?q=Prellerstr+14%2C+Dresden

The first above will not trigger Map and/or Places-Tab.
It is useless to trigger a searchrequest using contextmenu.

**Comment by bsstoner** [comment]
Thanks, these should work now.
