### ISSUE TITLE
Indeed Jobs: Need to provide empty string for subtitle to ensure consistent tile heights

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2393]
Some results don't have defined values for the subtitle, causing the tile heights to differ.

We need to pass along an empty string: ` ` as a fallback so that the template create a subtitle div which will ensure all the tiles have the same height.

![perl_jobs_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/12212815/88573c3c-b63c-11e5-9652-4ef78b6a40d8.png)

------
IA Page:  http://duck.co/ia/view/indeed_jobs

**Comment by davidofferman** [comment]
I was thinking we should modify the design slightly for this IA. Since a lot of terms for careers are long, having a `wide` tile instead of a normal width tilemay look nicer. 

Also changing the `tileTitle` to be `1line` instead of `2line` would get rid of the extra white space space between the job title and the company name. In your screenshot, look at the tile for "DB2 DBA" and "software architect".

[Before Design](https://cloud.githubusercontent.com/assets/14809478/12215904/fb1e141e-b69d-11e5-824d-fada48ff6f93.jpg)
[Updated Design](https://cloud.githubusercontent.com/assets/14809478/12215907/0975c598-b69e-11e5-95b7-475b530182c3.jpg)
