### ISSUE TITLE
NPM: add link for `git://github.com` URLs in Repository package information

### ISSUE THREAD

**Issue by cjs-cynic-net** [duckduckgo/zeroclickinfo-spice#2439]
@remixz 

The result of a DDG search for an npm module, e.g., ["npm tape"](https://duckduckgo.com/?q=npm+tape) returns a useful infobox at the right, generated from the `package.json` file.

When the URL for the repository, as specified in that file, is something like `git://github.com/substack/tape.git`, it's not a clickable link. (For this particular example, the "Source" field link, starting with `http`, is clickable.)

It shouldn't be to hard to determine that a `git` link links to a github.com repo, parse that link, and in the DDG infobox add an actual clickable link to the web page for that same GitHub repo (in this particular example, `https://github.com/substack/tape`.)

------
IA Page:  http://duck.co/ia/view/npm

**Comment by MrChrisW** [comment]
Hi @cjs-cynic-net thanks for your suggestion!

The reason the repository URL isn't changed is because it's a link to the "repository" which can be used in version control software. The infobox already contains a link to the projects homepage and in many cases this is a link to the github project page.

Like with the "npm tape" search
![2016-01-25-11-npm tape at duckduckgo](https://cloud.githubusercontent.com/assets/5282264/12553998/6c24f316-c3b5-11e5-9c99-abb9b6ed6a0c.png)

What might be beneficial is detecting if the "project homepage" differs from the repository link (eg does not contain github/bitbucket) and modify the repository link to http - a good example is ["npm bower"](https://duckduckgo.com/?q=npm+bower&ia=software)

However I think it's generally best to avoid modifying these links in a hardcoded way as in the future a new Git repository site may be used and we'd need re-implement the link parsing. It's best/simple to just use what the API sends.
