### ISSUE TITLE
Whois Spice: JS Error causing nothing to be displayed for valid domains

### ISSUE THREAD

**Issue by altern8tif** [duckduckgo/zeroclickinfo-spice#2467]
Suggestion to show "_domain name is available_" when whois query returns `null`.

---

IA Page:  http://duck.co/ia/view/whois

**Comment by jagtalon** [comment]
Hey, @altern8tif! It seems to already do something to that effect:

![screen shot 2016-02-08 at 6 49 45 am](https://cloud.githubusercontent.com/assets/81969/12885006/3ff47e80-ce30-11e5-8d60-b698d7b7bf34.png)

Was that what you were looking for or something different?

**Comment by altern8tif** [comment]
The results for the whois spice seems to produce very weird results.  It works for some domains but not for others.

Not sure if it's related to #2461.

Examples:
![screen shot 2016-02-08 at 10 44 37 pm](https://cloud.githubusercontent.com/assets/5793364/12888610/fb9b9cd8-ceb5-11e5-8c19-628623fdbdf6.png)
![screen shot 2016-02-08 at 10 44 49 pm](https://cloud.githubusercontent.com/assets/5793364/12888611/fd193890-ceb5-11e5-9ae9-6d9804ced734.png)
![screen shot 2016-02-08 at 10 45 51 pm](https://cloud.githubusercontent.com/assets/5793364/12888614/fea59c12-ceb5-11e5-9365-0cbb193d6052.png)
![screen shot 2016-02-08 at 10 47 01 pm](https://cloud.githubusercontent.com/assets/5793364/12888615/01168a60-ceb6-11e5-8c1e-a52d9fe4366f.png)
![screen shot 2016-02-08 at 10 47 28 pm](https://cloud.githubusercontent.com/assets/5793364/12888618/0308afa6-ceb6-11e5-95b4-604b7ddb3a05.png)

**Comment by moollaza** [comment]
@altern8tif good catch! It looks like there are JavaScript errors causing nothing to display in those cases.

We now supress the errors from showing in the console, but you can see them in the network tab:
![network_-_whois_randomname_io_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/12999815/463e48ae-d121-11e5-8ea0-8ce66170069e.png)

looks like there's an undef property/objects here. Care to investigate?

**Comment by sekhavati** [comment]
There seem to be a couple of issues here. #2507 fixes what @moollaza highlighted. However having resolved that we still end up not displaying a message to say the domain is available. This looks to be because of [this line of code](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/whois/whois.js#L122) in combination with the data returned. For the domains mentioned above the API results don't include a dataError property, hence the function returns false and we begin trying to show the whois info which isn't there.

The difference in API results can be seen here:
- https://www.whoisxmlapi.com/?domainName=asdfduckduckgo.com&outputFormat=json
- https://www.whoisxmlapi.com/?domainName=randomname.io&outputFormat=json

I'm not familiar with this API but a quick look at [their documentation](https://www.whoisxmlapi.com/documentation/whoisapi_documentation/index.html) suggests it should have that property set if the domain isn't registered, so this looks to be a bug on their part.

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
