### ISSUE TITLE
InTheaters: Firing off a lot of http requests when scrolling the carousel

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#2504]
Some of these are valid images it's loading, but then there's a ton of extra requests for some reason. Something seems wrong:

<img width="663" alt="screen shot 2016-02-12 at 7 29 27 am" src="https://cloud.githubusercontent.com/assets/126358/13006938/6eb782f8-d15a-11e5-9029-63be97caade8.png">

@jagtalon 

------
IA Page:  http://duck.co/ia/view/in_theaters

**Comment by jagtalon** [comment]
@bsstoner the issue was with the images being deprecated by RT, so we had to find an alternative source. What we're doing is RT's results combined with TMDB's images.

The issue can be found in https://github.com/duckduckgo/zeroclickinfo-spice/issues/1647

The fix was https://github.com/duckduckgo/zeroclickinfo-spice/pull/1840

**Comment by jagtalon** [comment]
@bsstoner there is an internal discussion about alternatives (read: business-y stuff)--we can move this discussion there.

**Comment by bsstoner** [comment]
:+1: thanks
