### ISSUE TITLE
Coderwall: IA Broken, API Response Format Changed?

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2548]
This IA is currently not working and there is a console error.

The Safari debugger suggests that the `$.each()` loop over `item.accounts` isn't working. 

It looks like the API response format has actually changed and now the code needs to be updated

------
IA Page:  http://duck.co/ia/view/coderwall
/cc @motersen

**Comment by xaviervalarino** [comment]
It looks like Coderwall flattened the API response, taking everything out of the `accounts` object. Luckily each key has the same name.

The description data also had to be massaged a little bit, as it now has links to other sites (LinkedIn, BitBucket, StackOverflow, etc.) in the string. I tested a simple split().shift() with a few usernames, and it seems to work.

Here is my diff: https://github.com/xaviervalarino/zeroclickinfo-spice/commit/01e459a455243b1c72f5aca6fc5220a0fc185ecb

**Comment by xaviervalarino** [comment]
After creating an account on Coderwall, I now have a better idea what is going on with the descriptions.
Coderwall allows markdown in their _about_ section, so people are using it to add links. 

![example-of-unparsed-md-links](https://cloud.githubusercontent.com/assets/4262486/13691528/6a72d3ec-e6ee-11e5-9a62-aee1d2ad6414.png)

I personally think this looks really bad. So here are two proposed solutions:

1. Strip out all markdown syntax, removing links. This could make the descriptions nonsensical if the link text is part of the sentence structure. (Conversely, could be confusing if left in, if it's not.)
2. Parse the markdown in `normalize`. This seems like it might not be as difficult as it sounds, since the md that is actually converted on Coderwall is limited. Unfortunately the `icon` template escapes any markup, so it wouldn't be as simple as just wrapping the text in `<a> `,`<em>`, and `<strong>` tags.

**Comment by xaviervalarino** [comment]
I have have created a custom handlebars helper to parse the markdown and pass it to a custom subtemplate in `content`. It relies heavily on regular expressions:
```js
    Handlebars.registerHelper("parseMD", function(content){
        if (!content) return;
        else return content.split(/\n+/).join('<br>')                 // replace newlines with line breaks
            .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')         // bold
            .replace(/(?:_(.+?)_|\*(.+?)\*)/g, '<em>$1$2</em>')       // italicize
            .replace(/`(.+?)`/g, '<code>$1</code>')                   // monospace
            .replace(/\[(.+?)\]\((http.+?)\)/g,'<a href="$2">$1</a>') // create links
            .replace(/<br>+$/g, '');                                  // trim trailing linebreaks at end
    });
```
@moollaza Should I submit a pull request?

**Comment by moollaza** [comment]
@xaviervalarino Thanks for looking into this!

>I now have a better idea what is going on with the descriptions. Coderwall allows markdown in their about section, so people are using it to add links.

Hmm, that's really annoying, especially considering that Coderwall already had a place for you to provide social links, which we detecting and putting into the subtitle.

@xaviervalarino I think we may have to go with your approach, but I don't like the idea of injecting links into the description...

**Comment by xaviervalarino** [comment]
@moollaza I see what you are saying about Coderwall injecting links into the description. I think people are mainly using this field for social links because there coderwall only has inputs for Github and Twitter on in account config.

I created another handlebars helper that strips out the markdown:
```js
    Handlebars.registerHelper("stripMD", function(content){
        var contentArr = [];
        if (!content) return;
        else content.split(/\n+/).forEach(function(line) {
            // exclude lines that are only whitespace characters
            if (/[a-z]/.test(line)) {
              
              line = line.replace(/^(\[[a-z0-9]+]\([a-z0-9\.\:\/\$-_\+\!\*',]+\) *)+?$/gi,'') // remove links not related to description
                .replace(/\[([a-z0-9]+)\]\(([a-z0-9\.\:\/\$-_\+\!\*',]+)\)+/gi,'$1')          // strip links that _are_ in description
                .replace(/(_(.+?)_)/g, '$1')      // strip italicize
                .replace(/(\*+(.+?)\*+)/g, '$1')  // strip bold
                .replace(/`(.+?)`/g, '$1');       // strip monospace
              contentArr.push(line);
            }
         });
         return contentArr.join('<br>') //add linebreaks
    });
```
And also added some a RegEx function to `normalize` that to pulls in any social links, although I don't think this expression is ready for production:
```js
normalize: function(item){
  ...
    // add social links that might be in the description
    item.about.split(/\n+/).forEach( function(line){
        var lineOfLinks = /^(\[[a-z0-9]+]\([a-z0-9\.\:\/\$-_\+\!\*',]+\) *)+?$/gi;
        // note: capturing groups are different!
        var singleLink = /\[([a-z0-9]+)\]\(([a-z0-9\.\:\/\$-_\+\!\*',]+)\)+/gi; 
        if (lineOfLinks.test(line)) {
            line.replace(singleLink, function(match, p1, p2) {
                subtitles.push({
                   href: p2,
                   text: p1
                });
            });                     
        }
    });
 ...
},
```
Here is a composite of screenshots of me testing a bunch of usernames on duckpan:
![coderwall-screenshots](https://cloud.githubusercontent.com/assets/4262486/13793859/4f054b28-eab6-11e5-9f4d-1d82fc866d3a.png)

**Comment by moollaza** [comment]
@xaviervalarino apologies for the delay and thanks for the excellent work! This is really awesome.

I'm not sure I love adding the additional links into the subtitle because we purposely chose to only put Twitter and GitHub there before (we were getting too many links in the subtitle and it didn't look great).

However removing them altogether and not displaying them seems sketchy.

I think for now we should go with the parsed markdown and potentially add some CSS to change the link colours (I suspect the design team would prefer that).

Judging by the size of the "descriptions" now, I think we may need to set `options.chompContent` to `true` so that larger paragraphs will be suppressed initially and a `Show More` button will be there to allow the text to be expanded.

@xaviervalarino can you please open a PR with your changes?

**Comment by xaviervalarino** [comment]
@moollaza I can implement your feedback on Monday and then create a PR. Would it be best to use the `zci__links` class?
