### ISSUE TITLE
ProductHunt: Tiles have inconsistent height

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#2595]
It looks like we need to set the `tileTitle` variant to `"2line"` so that the card height is consistent.

------
IA Page:  http://duck.co/ia/view/product_hunt 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sevastos

**Comment by rasikapohankar** [comment]
@moollaza : Hi! I tried fixing this. Adding tileSnippet to the list of variants is making the heights consistent, since it was the product description that had a different number of lines for some of the tiles, tried with both tileSnippet as small and large,  What do I do next? How to verify that this will work for all kinds of queries?

**Comment by moollaza** [comment]
> What do I do next?

It looks like it's been merged, so I'd say give yourself a pat on the back! Thanks again for fixing that bug!

**Comment by rasikapohankar** [comment]
@moollaza : Thanks for the encouragement! :smile:
