### ISSUE TITLE
Kwixer: feedback from user

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-spice#2710]
A user on DuckDuckGo sent us feedback regarding the IA missing some high-profile movies for popular actors and actresses.     

------
IA Page:  http://duck.co/ia/view/kwixer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rodrigue-h

**Comment by rodrigue-h** [comment]
Hello,
Unfortunately we started shutting down Kwixer as a whole (which is why
we're not grabbing/ updating new movies)
I suggest we remove the Kwixer IA ?
Thanks,
Rod


On Mon, Apr 25, 2016 at 11:38 AM, Bill <notifications@github.com> wrote:

> A user on DuckDuckGo sent us feedback regarding the IA missing some
> high-profile movies for popular actors and actresses.
> ------------------------------
>
> IA Page: http://duck.co/ia/view/kwixer
> Maintainer <http://docs.duckduckhack.com/maintaining/guidelines.html>:
> @rodrigue-h <https://github.com/rodrigue-h>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/duckduckgo/zeroclickinfo-spice/issues/2710>
> Untracked with Trackbuster <https://trackbuster.com/?sig>
>



-- 
-- 
Best Regards,
Rodrigue H.
http://www.twitter.com/rodrigue_
http://www.rodrigueh.com

**Comment by moollaza** [comment]
@rodrigue-h I'm sorry to hear that, but thanks for letting us know. I'll make a task to remove the Instant Answer.
