### ISSUE TITLE
RedditSearch/Images: deficiency in triggering

### ISSUE THREAD

**Issue by asb** [duckduckgo/zeroclickinfo-spice#2798]
Behaviour here seems somewhat random. Sometimes searching for 'reddit doom glium' triggers the image instant answer instead of reddit, sometimes it doesn't. Same with 'reddit doom on glium'.

------ 

IA Page: https://duck.co/ia/view/reddit_search

**Comment by edgesince84** [comment]
I'll test this out a few more times and see if I get anything different.

cc @mattr555 // @majuscule

**Comment by moollaza** [comment]
I have found the Reddit API to respond quite slowly before. If it takes too long to respond, we'll show another Instant Answer instead of waiting (potentially forever...) to show the IA that has triggered. This may just be an issue we need to tolerate, unless we can get Reddit to improve their API's response time

**Comment by asb** [comment]
@moollaza That would explain the inconsistency. As a user, I find that behaviour unintuitive though. This perhaps isn't the right place for this discussion, but perhaps there could be a way of showing in the UI that another IA is currently loading? What is the current API timeout?

**Comment by moollaza** [comment]
> but perhaps there could be a way of showing in the UI that another IA is currently loading?

Unfortunately that's not exactly an option, because there's the chance that once we received the API response, it may not be relevant and so the IA will choose not to show anything. If we told the user it was loading but then had nothing useful, that may lead to further confusion. In some cases, there are many IA's that trigger but only a few that show a result so it would be hard to handle. This is why we try to ensure all the APIs are returning results very quickly.

> What is the current API timeout?

The default timeout is 5s, but we aim for < 1s responses, which most IAs handle. Occasionally some may go over, but anything consistently slow should be reviewed and fixed/removed as necessry.

**Comment by moollaza** [comment]
IA is no longer online
