### ISSUE TITLE
Difference between SearchCode and CodeSearch IA

### ISSUE THREAD

**Issue by sahildua2305** [duckduckgo/zeroclickinfo-spice#2825]
I am confused about these Instant Answers. Both use the same API, same endpoint and have somewhat similar triggers as well.
@boyter

**Comment by boyter** [comment]
One was documentation search the other code. They do look similar. The one
with codesearch in the url is the one to keep however as the other is all
available as fathead queries.

Forgive the brevity have spotty internet atm as in Fiji.

**Comment by sahildua2305** [comment]
@boyter Sorry, it's still not clear to me.
Can you please clarify which one is for documentation search and which one is for code search?

I am specifically confused because both the IAs use the same endpoint for codesearch. :confused:

**Comment by moollaza** [comment]
@sahildua2305 SearchCode is the original IA and is used to search through Documentation. It has some overlap with our Fatheads, but not entirely. Ideally Fatheads should be used to replace SeachCode, (docs lookup) because docs are mostly static and our Fatheads can be re-run yearly to keep them up to date.

CodeSearch is intended to search through code snippets to find example usages of a given function/method/etc
