### ISSUE TITLE
People In Space: Show previous people in space

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2839]
Not sure if this is possible with the current API, but it would be nice to see the list of people continued to show people who were in space, perhaps greyed out or otherwise de-emphasised.   

---

IA Page:  http://duck.co/ia/view/people_in_space 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @elebow

**Comment by elebow** [comment]
As far as I know, the upstream API doesn't provide this information. This might be a good feature to suggest to them, though. Then we'd be able to use it easily.

The question of presenting the additional information is nontrivial. Since the number of people that have ever been in space is [hopefully] unbounded, it will need to be scalable. I presume some sort of grid layout with pagination is best, but that might not be possible with the current IA platform... not even image and video search show more than a single page of results.

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
