### ISSUE TITLE
Timer: Does not ringing when browser tab is unfocused

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-spice#2886]
A DuckDuckGo user has reported that the timer does not ring until the tab is in focus, using Ubuntu 14.04, Chromium XXX

---

IA Page:  http://duck.co/ia/view/timer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by tagawa** [comment]
I've been able to reproduce this as well using Vivaldi 1.3 on Mac OS X, but it only happens when I open a new tab to run the timer. It then works fine after reloading or re-running the query.

**Comment by Hum4n01d** [comment]
Same issue. I use this time all the time but I don’t know when the timer’s gone off :(

**Comment by ajhepple** [comment]
I've experienced this with Chrome on Ubuntu and have done a little experimentation.

I think it only occurs when a timer instance is first used and when that timer's tab is not uppermost (or its window minimised) when the timer reaches zero. 

The timer will sound without focus, providing it's tab is uppermost. For example, in a different window to the window with focus.

Timer instances always appear to sound when reset and restarted. Whatever their tab position or window state.

As a workaround, I suggest creating a new browser window exclusively for a timer. Let it fall, hidden behind any number of windows, but don't minimise it.

**Comment by CreamyCookie** [comment]
It works on Firefox in Ubuntu 16.04, so it's likely Webkit related. Anyway, I also wanted to say thanks for this great, zero-click thingie @mattr555

**Comment by moollaza** [comment]
I'm seeing this on FF Dev edition when the tab is not focused. The tab does show an icon indicating that a sound is playing, but its not audible until the tab is focused. 

Notably, Google's timer does manage to produce a sound when the tab is not focused.

**Comment by Benzer1406** [comment]
Doesn't work with Ubuntu 20.04 LTS and Brave (Chromium). Doesn't ring when not focused.

**Comment by moollaza** [comment]
I've confirmed that the likely cause of the issue here is that most browsers won't play audio if the tab has not received some kind of user interaction. This affects Google's timer as well and I don't see any solution that ensures the audio will play. 

You can test this by searching from the URL bar for "timer 2s" or "!g timer 2s". In both cases if you don't click the page the audio will not play. Firefox shows on the left hand side of the URL bar that autoplay audio is not enabled. If the user manually enables audio/video to play on the domain it's no longer an issue.

I don't see any way to guarantee audio will play, however we could show a banner/notification asking the user to click the page to ensure the audio can play.

With DDG in maintenance mode though, I don't consider this urgent so I don't expect any changes/fixes to be made here.

**Comment by Benzer1406** [comment]
@moollaza  Using the same browser and OS I have no issues with the google timer. It plays even though the tab is not focused.

**Comment by moollaza** [comment]
@Benzer1406 how are you starting the timer? If I search from the DDG homepage "timer 5s" then open a new tab and continue interacting with the new tab the audio plays for me on Chrome/FF/Brave on my Mac.

The same is true for Google, because the page has had interaction.

If I search through the address bar for both, regardless of default search engine, then open a new tab without clicking in the page, in both cases I'm able to get the audio to _not_ play, because the tab didn't have sufficient focus.

I don't have access to Ubuntu, but I would expect the same behaviour there.

**Comment by Benzer1406** [comment]
@moollaza I didn't even know about the feature of the address bar, like that. 

**DuckDuckGo:** Unfortunately, either way leads the timer sound NOT to play from DuckDuckGo. 
**Google:** When going to google.com and configuring the timer, immediately changing the tab, does PLAY the sound. When using the address bar feature it indeed does not play.

I usually had the google timer in a pinned tab and it used to work, but DuckDuckGo does not.

**Comment by moollaza** [comment]
@Benzer1406 a colleague was able to confirm that Brave on Ubuntu seems to behave differently than all others.

I suspect it may be the way we're loading the sound library only at the time the audio plays, and so on subsequent attempts to play the sound while the tab is unfocused, everything works as expected.

DDH is in maintenance mode though, and becase this appears to be a non-critical edge case, we'll have to tolerate this bug for now.

**Comment by Benzer1406** [comment]
@moollaza Thanks for checking and confirming. Yeah, don't worry, it's probably an idiosyncratic phenomenon of Brave. I just went back to use Google Timer while still using DuckDuckGo as my default search engine.

**Comment by jacobgkau** [comment]
> DDH is in maintenance mode though, and becase this appears to be a non-critical edge case, we'll have to tolerate this bug for now.

Having just burnt some food because your timer doesn't work when the tab isn't focused, I would disagree with your assessment that this is a "non-critical" issue (or an edge case in any way.)
