### ISSUE TITLE
CodeSearch: API Sending 500 Errors

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#2895]
Hi, @boyter!

It looks like we're getting a 500 error when hitting https://searchcode.com/api/jsonp_codesearch_I/?q=lang%3Ajavascript%20console.log&callback=ddg_spice_code_search:

<img width="815" alt="screen shot 2016-07-13 at 10 48 46 am" src="https://cloud.githubusercontent.com/assets/81969/16813647/68dbc362-48e7-11e6-9e96-bec54d34b63d.png">

<img width="990" alt="screen shot 2016-07-13 at 10 47 19 am" src="https://cloud.githubusercontent.com/assets/81969/16813641/5db6b21c-48e7-11e6-9495-52a4c0f6953f.png">

Do you see the same problem?

Thank you, and have a good day!

https://duck.co/ia/view/code_search

**Comment by boyter** [comment]
Sorry I was literally in the middle of nowhere hiking. Im fixing it now. I am planning on moving over to newer more reliable servers soon which should resolve these issues for good.

**Comment by boyter** [comment]
There. Should be fixed. I think this should be ok to close now.

**Comment by edgesince84** [comment]
hey @boyter was there a PR for this?

**Comment by boyter** [comment]
@edgesince84 No. It was all due to the searchcode.com endpoint itself failing. Hoping to have moved over by the end of the week to resolve these issues for the long term.

**Comment by edgesince84** [comment]
thanks @boyter - looking forward to a resolution!

**Comment by boyter** [comment]
Well this is done. It should be FAR more reliable now... and a lot faster to boot. Let me know if that is not the case though.

**Comment by moollaza** [comment]
@jagtalon can you confirm it's working again?

**Comment by jagtalon** [comment]
This works! Thank you, @boyter! How was the hike? :muscle:

**Comment by boyter** [comment]
@jagtalon to be honest not brilliant! 160km gusts of wind, 30mm of rainfall, hail the size of grapes and it was -17 with the windchill. Had to bail after the first night because of how insane the weather was. Stayed in a cabin at the trailhead and it got even worse that night so it was the right choice.

However I did make it to the southernmost point of the Australian mainland and managed to find the geocache down there as well which was nice. Better yet I get some great stories out of it so there is that!

**Comment by boyter** [comment]
Oh I should mention I have the CORS header set for this now, so you don't need to use the JSONP endpoint anymore if you would prefer not.
