### ISSUE TITLE
JavaScript: Gulp Spice under-triggering

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-spice#3099]
## Description

It seems from the search data that people are searching for `gulp <package_name>` more so than `gulpjs <package_name>`. It could be a good idea to add it to the triggers.

## Steps to recreate

Example search: https://duckduckgo.com/?q=gulpjs+sass&t=h_&ia=software

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/gulp

**Comment by csu** [comment]
I think this would be a good change to make (I'd search for just `gulp` and not `gulpjs`). I can make the change. Do you think this could potentially trigger on any non-Gulp.js-related queries with `gulp`? Would it be better to add `gulp` as a `startend` trigger?

**Comment by adityatandon007** [comment]
Hey @jagtalon, Can I work on this issue. I am beginner and would like to take this issue.

**Comment by moollaza** [comment]
@adityatandon007 Yes you're welcome to work on it!  (Jag works for DDG, so he's happy to have you take this on for him 👍 )

**Comment by jagtalon** [comment]
@adityasangar eyo! Go ahead!

**Comment by adityatandon007** [comment]
hey @jagtalon you mistyped my name I think. Well thanks for assigning me this task. One more can you assign a label to it.

**Comment by adityatandon007** [comment]
Thanks @moollaza for adding me to become the part of duckduckgo organisation. I want to ask why we don't always label assignee on someone working on the issue. In many cases assignee label is not put even though, when I scroll down someone is working already working on it. Why is it so that sometimes there is label and sometimes not. Just curious. One more think can you please send me some links about our testing environment (Travis CI). I want to know how it works internally, because sometimes people make PR but Travis CI report one test failed and person who made the PR has hard time to work it out. Also it would be good if we could add some links of Travis in our duckduckhack documentation. :+1)

**Comment by adityatandon007** [comment]
Thanks @tagawa. Could you review my PR and thanks for that assignee label. Well it looks someone do care about these minute issues like assigning labels.

**Comment by pjhampton** [comment]
@adityatandon007 all issues are important, however, community leaders and staff need time to review other PRs too. We can't always label a person an assignee because they don't belong to the github organization. We also have a process were the IA maintainer is assigned automatically when an issue is raised hence why Jag why assigned. One of the curators (such as myself) can only assign someone to an issue when we see it. Thanks for your patience.
