### ISSUE TITLE
Timer: Not working in dark theme?

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#3102]
User feedback:
_When using the timer the"Add Timer" button doesn't work with the dark theme, it just looks pure empty white 😞_   

------
IA Page:  http://duck.co/ia/view/timer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by akanshgulati** [comment]
Could you attach a screenshot of the issue. I can see the "plus" button very clearly.

**Comment by bsstoner** [comment]
I think they're talking about on mobile.

**Comment by bsstoner** [comment]
<img width="364" alt="screen shot 2017-01-23 at 8 40 24 pm" src="https://cloud.githubusercontent.com/assets/126358/22230536/31f9c746-e1ac-11e6-88bc-3d507d4aa5c2.png">

**Comment by moollaza** [comment]
@bsstoner this may be an internal CSS bug -- our our `tx-clr--*` class here is being overwritten by our `.zci-bosy a` rule that sets the color.

We need to give priority to our `tx-clr` classes, otherwise we'll need to write CSS to change the text color here based on the presence of the dark theme's class on the `<body>` tag

**Comment by bsstoner** [comment]
@moollaza I don't think that's the case. Why are we overriding the background color here? If you didn't do that it would work: https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/timer/timer.css#L351

**Comment by nalinbhardwaj** [comment]
Fixed via #3134. Please review.
