### ISSUE TITLE
Currency Conversion: Enable space to be used as thousands separator 

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#3109]
Example:

**1 459 000 RUB to USD**
[https://duckduckgo.com/?q=1%20459%20000%20RUB%20to%20USD&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=1%20459%20000%20RUB%20to%20USD&kp=1&kad=wt_WT&kl=wt-wt)

<img width="852" alt="screen shot 2017-01-21 at 10 03 32 am" src="https://cloud.githubusercontent.com/assets/126358/22175342/ee6b99d8-dfc0-11e6-9554-8c7c7f25de4b.png">

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by adityatandon007** [comment]
@moollaza I thing we should close this for now. Because this IA is not designed to take into the account things like spaces. If it is so then someone can also say that it doesn't work when tabs are included in amount or any unprintable character. 
The IA's are just meant to trigger for only those things which they say, otherwise we loose on accuracy just to cover something which is not relevant at all.

**Comment by btrower** [comment]
Don't close. One of the things that make other engines (say, Google) so compelling is that they do their best to anticipate what you want based on input that you actually give, rather than what designers specify in advance. Exact syntax is for compilers, not human beings.

**Comment by moollaza** [comment]
@mintsoft can we adjust the NumberStyle to allow a space as a thousands separator?

Additionally a quicker fix would be to replace or remove spaces between numbers in the query:

E.g. `s/(\d+)\s+(\d+)/$1,$2/

**Comment by mintsoft** [comment]
@moollaza yeah that's pretty easy to do; is the NumberStyle available to the perl backend of a spice though?

**Comment by BillyBarbaro** [comment]
The Conversions IA @mintsoft mentioned is a Goodie, while the Currency IA is a spice.  The NumberStyle module (? sorry, not that familiar with Perl terminology) differs slightly between the two.

[Spice NumberStyle](https://github.com/duckduckgo/zeroclickinfo-spice/blob/5e1b8cca1dadc5e1d33ac9a536058d5180bdfa74/lib/DDG/SpiceRole/NumberStyle.pm)
[Goodie NumberStyle](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/ba2760f03485f32f10de1e85c19b11415cb8528b/lib/DDG/GoodieRole/NumberStyle.pm)

If you take a look at the history of both of these files, it seems like the Spice version of this was just copied over from the Goodies repo in October of 2014.  Since then, there's been a few commits to the Goodies version of the file (e.g. adding support for space & underscore separation) but the Spice version has not received these patches.

**Comment by mintsoft** [comment]
@BillyBarbaro Thanks for that! I wasn't aware that the `NumberStyle` Role has been copied into this repo

@moollaza It's probably best to get https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4000 merged and then we can update the Spice repo's copy of the Role for now?

**Comment by moollaza** [comment]
> It's probably best to get duckduckgo/zeroclickinfo-goodies#4000 merged and then we can update the Spice repo's copy of the Role for now?

@mintsoft sounds good!  duckduckgo/zeroclickinfo-goodies#4000 is merged 😄
