### ISSUE TITLE
Geometry: wrong format?

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#3138]
**sphere volume formula**
[https://duckduckgo.com/?q=sphere%20volume%20formula](https://duckduckgo.com/?q=sphere%20volume%20formula)
_When 'sphere volume formula' is searched the formula shown by the browser at the top of the search results page is misleading. It shows V=4/3pi()r^3. The idea is correct but the format is wrong in my opinion. It should be shown that pi*r^3 is separate from 4/3 in this format. A more accurate portrayal would be (4/3)*pi()*r^3. Here is the LaTeX if it helps: \\frac{4\\pi{r}^{3}}{3} . I love the Duck Duck Go browser and everything it stands for. Keep up the good work! I appreciate you guys!_

------
IA Page:  http://duck.co/ia/view/geometry 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pixunil

**Comment by pjhampton** [comment]
I'm not really sure about this. It's more of a _slight_ preference. Google have a similar IA where the formula is the same. Due to this being a spice, we would also have to take the input and reformat it. 
![screen shot 2017-03-02 at 2 55 36 pm](https://cloud.githubusercontent.com/assets/8960296/23512594/108f5b78-ff59-11e6-90aa-0eeb208b7916.png)

**Comment by pjhampton** [comment]
Closing. Opened https://github.com/duckduckgo/zeroclickinfo-spice/issues/3166
