### ISSUE TITLE
ExpandURL: Not working with amp.gs

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#3144]
**expand url amp.gs/15W2**
[https://duckduckgo.com/?q=expand%20url%20amp.gs%2F15W2](https://duckduckgo.com/?q=expand%20url%20amp.gs%2F15W2)
_Comment: "expand url" is not working with amp.gs_

------
IA Page:  http://duck.co/ia/view/expand_url 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @adman

**Comment by nalinbhardwaj** [comment]
It seems the LongURL API is down. The results that are being displayed are due cache. The IA would probably need a rewrite.

**Comment by moollaza** [comment]
The API response, and untiny.me explain that amp.gs is an unsupported service. So this isn't a problem we can solve unless there is a better URL Expanding API.

FWIW Chrome and Safari suggest you don't visit untiny.me because the site was apparently detected as containing malware.

Closing this and creating a new task to find a better API.

**Comment by moollaza** [comment]
New issue: https://github.com/duckduckgo/zeroclickinfo-spice/issues/3164

**Comment by moollaza** [comment]
Fixing in https://github.com/duckduckgo/zeroclickinfo-spice/pull/3206
