### ISSUE TITLE
SoundCloud: Stream Unavailable at replay.

### ISSUE THREAD

**Issue by dShringi** [duckduckgo/zeroclickinfo-spice#3149]
If you try to replay the song you have listened once, it doesn't plays and you get Stream Unavailable. To replicate the same, just search and play any soundcloud audio and once it is completed, try to play it again.   

------
IA Page:  http://duck.co/ia/view/sound_cloud 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jdan

**Comment by adityatandon007** [comment]
@pjhampton I couldn't replicate the same. It seems to be working fine for me.

**Comment by dShringi** [comment]
@adityatandon007 @pjhampton Based on the above comment I tried with couple of more songs and it worked for most of the cases however I tried to replicate with the ones I had faced the issue and I could replicate the issue.

So, I have attached the evidence, can you please try to replicate with the attached evidence and confirm if it still works for you or not.

![stream_unavailable](https://cloud.githubusercontent.com/assets/3148599/23133134/fa201a04-f787-11e6-9266-703948b03b10.png)

**Comment by adityatandon007** [comment]
@dShringi No luck buddy, I was not able to replicate the issue with song you mentioned. I tried 2 times but for me its working properly, though I would like to ask you in which browser you tried. I only tried in chrome and its seems to be working fine in chrome. Could you tell in which browser you tried :question:

**Comment by adityatandon007** [comment]
@dShringi One slight luck I was able to replicate the issue on firefox but its not an issue. I get the stream unavailable if I am streaming something else on other webpage like youtube and I think this happens because of the limited bandwidth (download/upload), else its working fine. Hope this helps. Still I would love to know the browser in your case. One more thing you can try clearing the cache too.

**Comment by adityatandon007** [comment]
@dShringi @pjhampton some more testing on chrome also show this problem of _stream unavailable_ if you continuously listen to the song for a very long time like replaying the song 3 or 4 times and it goes then for every song, but disconnecting the network and reconnecting the network again solves the issue but I don't know exactly why this happens. Might be something off with the API **(clearly not bandwidth issue)**

**Comment by dShringi** [comment]
@adityatandon007 You're right in saying that it is not a bandwidth issue. I just tried to see if I could find anything in developer console and I found that the media request on subsequent call fails with `403 x-cache:Error from cloudfront`. So, it seems like an issue with soundcloud api, not sure though.

**Comment by adityatandon007** [comment]
@dShringi This issue is getting more annoying now. It now shows `stream unavailable` for the first attempt of playing of some songs (sometimes). There is something going on with the Api. Soundcloud api doesn't seems to response. I am also getting `502 error` . I think it is some kind of resource conflict or port request issue, though not quite sure, I will ask about this issue with other community members.

**Comment by dShringi** [comment]
@adityatandon007 Now that is strange, before posting I tried couple of times but I never got 502. Also, I have never seen Stream Unavailable when I play the song first time. I will continue to use it and keep you posted if I face anything similar, anyway, agreed that it seems like an issue with the Soundcloud API only.

**Comment by Duncskunk** [comment]
A few days ago, when I would access SoundCloud through DuckDuckGo, it would allow me to listen to songs that I hadn't paid for and that were not available in my area. I assume because they were being streamed through someone else's account which may be a reason for soundcloud to block that account, potentially. I don't really know how DuckDuckGo is coded for streaming with SoundCloud.

**Comment by moollaza** [comment]
Thanks for pointing this out. We're investigating the issue.
