### ISSUE TITLE
Empty results array in API

### ISSUE THREAD

**Issue by artur99** [duckduckgo/zeroclickinfo-spice#3212]
## Description
The results given by the JSON api sometimes are empty. Same query on the full site would return the wanted results.

### Example
Term searched: 5941143004256
Full site(4 results): [https://duckduckgo.com/?q=5941143004256](https://duckduckgo.com/?q=5941143004256)
API request(no results): [https://api.duckduckgo.com/?q=5941143004256&format=json](https://api.duckduckgo.com/?q=5941143004256&format=json)
Also, the same error seems to appear if I access the html-only version
HTML-only request(1 result): [https://duckduckgo.com/html?q=5941143004256](https://duckduckgo.com/html?q=5941143004256)

---

Instant Answer Page: https://duck.co/ia/view/{ID}

**Comment by moollaza** [comment]
@artur99 the API you see is our Instant Answer API. It only provides some of the Instant Answer results we show on DuckDuckGo.com -- it does **not** provide link results as we do not have the syndication rights for them.

You can learn more about it here: https://duckduckgo.com/api

The additional links you see on DuckDuckGo.com are due to additional API calls we make to get more results in certain cases. This is done via JavaScript so we can't do this for the HTML version of DuckDuckGo
