### ISSUE TITLE
IsItUp: Doesn't trigger for some popular sites

### ISSUE THREAD

**Issue by adityatandon007** [duckduckgo/zeroclickinfo-spice#3276]
**Issue:** This IA should trigger but it doesn't for some websites.

**Steps to recreate:** 
For example: `is imdb working` doesn't trigger this IA
and this IA doesn't take spaces into account too.

------
IA Page:  http://duck.co/ia/view/is_it_up 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rasikapohankar

**Comment by rasikapohankar** [comment]
Hi @adityatandon007, the IA returns without an answer if the length of the website name is less than 5 and there is no TLD mentioned. `is imdb.com up` will give an answer, but `is imdb up` doesn't because `imdb` length < 5.

It seems this was decided to avoid false triggering on queries without TLD mentioned [here].(https://github.com/duckduckgo/zeroclickinfo-spice/pull/2517)

**Comment by adityatandon007** [comment]
@rasikapohankar I think `length < 4` should be better approach because there are many genuine websites with `length = 4` and so it would be nice for this IA to trigger for those websites in cases `TLD` is not mentioned. For example: `is bing up` doesn't trigger either.
![screenshot from 2017-05-10 13-37-38](https://cloud.githubusercontent.com/assets/25108385/25889157/6769a4fe-3586-11e7-9b90-bcb42f7f93dc.png)

P.S. It would be great for this IA to cover up for these websites. these are some genuine and hugely popular sites. 
What's your say on this @moollaza ?

**Comment by rasikapohankar** [comment]
@adityatandon007 I do not know how much of an advantage or disadvantage changing the check on length will have. I referred [this](https://moz.com/top500), there seem to be not too many sites with length less than 5. I'm okay with changing the check to `< 4`.
Or we could list sites which are popular and go ahead with the API call for those, even if a TLD was not present and the length was less than 5.

**Comment by moollaza** [comment]
> Or we could list sites which are popular and go ahead with the API call for those, even if a TLD was not present and the length was less than 5.

That sounds like a simple, reasonable solution. It should be easy to get a list of the top 1-500 domains, and remove any that are more than 4 characters long 👍

**Comment by adityatandon007** [comment]
@rasikapohankar I am fine with whatever solution you go with. Its just that I wanted this IA to cover up as many sites as possible (especially, the more popular ones)

**Comment by nalinbhardwaj** [comment]
@moollaza @rasikapohankar I was thinking that for the URLs in top 500 ranking, we should also check and not default to `.com` for suffixes, as that makes more sense(yandex **.ru**, w3 **.org** etc.).

I have put up a list of these websites extrapolated from [Moz](https://moz.com/top500) and [Wikipedia](https://en.wikipedia.org/wiki/List_of_most_popular_websites), sorted it, and removed duplicates and put it [here](https://gist.github.com/nalinbhardwaj/5f1d35a5dda878b2edfaef0191145381). Websites like URL shorteners etc. need to be manually removed(which should cut down the list by 100 URLs or so I estimate). If the list is okay otherwise, I will do that and make a PR.

**Comment by moollaza** [comment]
Closing due to DDH entering [Maintenance Mode](https://duckduckhack.com/). We are now only accepting issues for essential bugs/fixes.
