### ISSUE TITLE
Github Bug: Example query not triggering

### ISSUE THREAD

**Issue by kirkins** [duckduckgo/zeroclickinfo-spice#3360]
### Description

One of the examples on the IA page isn't working. The query is "github zeroclickinfo", I thought maybe it was intended to be used with a github username like "github duckduckgo" but that doesn't seem to trigger the IA either.

## Steps to recreate

https://duckduckgo.com/?q=github+zeroclickinfo&ia=web

Attempted query on beta and live version, not working on either.

## People to notify

#3342

---

Instant Answer Page: https://duck.co/ia/view/github

**Comment by adityatandon007** [comment]
@kirkins @pjhampton this is not a bug. This IA is working fine. The problem is there is no such thing (repository) as **zeroclickinfo** so the IA didn't trigger. @kirkins if you try with *zeroclickinfo-goodies* or *zeroclickinfo-spice* it triggers. 
![screenshot from 2017-07-15 19-49-59](https://user-images.githubusercontent.com/25108385/28241379-0c13904c-69b1-11e7-9d13-cd8e80f399fb.png)

Although,there is slight issue with this IA, it shows the answer but you have to click that software tab to see the IA result. I think we need to set the high signal for this.
![imageedit_1_5082348905](https://user-images.githubusercontent.com/25108385/28241421-961530ac-69b1-11e7-93e7-c96808cf337a.gif)

**Comment by adityatandon007** [comment]
@pjhampton I was thinking that duckduckhack should have a new repository for issues like this where people can submit the PR for things like description and example correction, so that even people with no programming background can contribute to the IA and we can expand the duckduckgo community too.
