### ISSUE TITLE
Currency Suggestion: Recognise "k, m, b" as amount suffixes

### ISSUE THREAD

**Issue by nalinbhardwaj** [duckduckgo/zeroclickinfo-spice#3374]
### Description

Currently, the IA doesn't get triggered if you search for something like `$2k in INR`, but does for `2k USD in INR`, so the first case should also be added(not very hard).

## Steps to recreate

[$2k in INR](https://duckduckgo.com/?q=%242k+in+INR&t=h_&ia=web)

## People to notify

@MrChrisW

---

Instant Answer Page: https://duck.co/ia/view/currency

**Comment by pjhampton** [comment]
@nalinbhardwaj do you want to patch this?

**Comment by nalinbhardwaj** [comment]
@pjhampton Na. Someone else should take it up.

**Comment by adityatandon007** [comment]
@pjhampton I think it shouldn't trigger this because the query which @nalinbhardwaj asked was very generic. 
Asking `$2k in INR` is very generic. 
If your solution will be defaulting it to USD then it might offense other users who can complain why not default to Australian dollar and right now duckduckgo defaults a lot of thing wrt to American results. 

Its just my point of view and you might disagree but I think its still good to ask others about what they think before we implement the solution.

**Comment by pjhampton** [comment]
I somewhat agree - but it's not a bug, it's a feature. This is why we're not rushing to implement it. It would be a bug if there were actually anybody searching for this. This IA is triggering 16,000+ times a day and very little searches have these suffixes. On the otherhand, seeing something is better than seeing nothing.

I will downgrade the priority and keep an eye on the feedback / search data. I can implement it once I have time but will keep it at low priority.

**Comment by kirkins** [comment]
@adityatandon007 as a Canadian I disagree with the idea that defaulting to USD is a problem. The USD is a sort of universal standardization. If I'm not on a Canadian site I know prices will be displayed in USD and I usually have a rough idea of what the price is in CAD if I see USD.

I'm more interested in consistency in a site rather than seeing CAD prices. Either always show me USD by default or always show me CAD. If you show me CAD on one spice but USD on another that is when I become confused.

**Comment by adityatandon007** [comment]
@pjhampton I think the title should be changed to something else. It does recognise `k, m, b` as amount suffix. Its the `$` thing in question here.

![screenshot from 2017-07-24 18-56-27](https://user-images.githubusercontent.com/25108385/28525426-d9ff66b0-70a1-11e7-9092-721219899b23.png)

**Comment by bradarv90** [comment]
@adityatandon007 That's correct. This appears to be the section of code that handles the `k, m, b` suffixes (https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Currency.pm#L209)
