### ISSUE TITLE
IsItUp: "Is melpa.org up" triggering image search, not IsItUp

### ISSUE THREAD

**Issue by jgkamat** [duckduckgo/zeroclickinfo-spice#3433]
Hi, sorry if this is being reported in the wrong place or in the wrong way.

The search `is melpa.org up` or `is melpa.org down` doesn't seem to trigger the IsItUp IA, and instead shows images instead.
![2017-09-29-003909_999x364_scrot](https://user-images.githubusercontent.com/4349709/31001042-9fcc6042-a4ae-11e7-9655-fd8d254a61c2.png)

It also seems to be conflicting with the github IA. `Is melpa.org up` (capital `I`) gives:

![2017-09-29-003942_938x288_scrot](https://user-images.githubusercontent.com/4349709/31001057-b6e30fce-a4ae-11e7-99c4-7640fc233af3.png)

This dosen't feel like an issue with the IA itself, but a conflict between two IA's? I'm not sure exactly how they work.

Related to #3276 

------
IA Page:  http://duck.co/ia/view/is_it_up 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rasikapohankar

**Comment by rasikapohankar** [comment]
Hi @jgkamat, the IA is getting triggered but is not getting shown. In the screenshot, there is the 'Answer' tab which will have the IA result. 
I don't really know why one IA gets priority over the other at times, its a race condition, from what I have read in other issues.

**Comment by jgkamat** [comment]
This definitely seems like a race condition (sorry, I editied my image, because I thought I reported the issue wrong). Upon a closer look , it seems like waiting a bit and re-running the search seems to have different things trigger (github IA, pictures, etc). I can't ever seem to get the IsItUp IA working though.

I guess this isn't really an issue in the IA then, so feel free to close this if you wish (but it would be nice to fix this one way or another).

**Comment by moollaza** [comment]
I'm not seeing any issues on my end. I see the tab with or without the capital I.

There is a race condition: we show the tab to whichever responds first, but are able to give certain tabs higher priority. IsItUp needs to make an API call, so depending on the user's internet it could take longer for the response and hence the tab might not show. We don't think we cache the API response for IsItUp which means it can vary at any time.

I don't believe there's a bug here, rather expected behavior.
