### ISSUE TITLE
Currency Conversion: Should indicate ounce to gram conversion

### ISSUE THREAD

**Issue by hikeislife** [duckduckgo/zeroclickinfo-spice#3451]
yeah, so, I looked up gold and silver, and instant answer gave me the price of ounce of gold and silver in my local currency. now, no one wants the search engine to tell them so blatantly it knows where you are searching from, but it's kind of made dumb by the fact that it used ounce. where i live, we don't use ounces for anything. i have no idea what an ounce is, really. grams. grams i understand. this type of fail reminds me of the time when searching we of the time when searching weather on yahoo, used to give me current temperature in my town (creepy), but it did so in the useless fahrenheits (dumb), which no one even uses, and are basically indecipherable for anyone who's not american. if yahoo knew exact city and district i was in, it was supposed to know I want have any use from fahrenheits, similarly to how you should know i have no way of knowing what ounce is. 

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by divyanshu97** [comment]
Hello @pjhampton @hikeislife 
Are you currently working on the issue. I want to contribute for the same.

**Comment by pjhampton** [comment]
Hey guys,

I'm not really involved with the DDG community atm because it would really just be me and that would suck... but I can reply to this as I worked quite extensively on this IA.

  1. When precious metals such as gold/silver are traded on fx/commodity markets their spot price are ounce backed. It's a financial standard. Pricing on grams makes no sense I'm afraid. 

  2. DDG don't know where you live, what street you live on etc. They don't record/need that information. However, they can **[like any website]** use your IP address at runtime to make subtle improvements to the experience of some instant answers. 

@divyanshu97 You may wish to check out https://github.com/duckduckgo/zeroclickinfo-spice/issues?q=is%3Aissue+is%3Aopen+label%3A%22Status%3A+Needs+a+Developer%22
