### ISSUE TITLE
Actor Filmography: 

### ISSUE THREAD

**Issue by danielfranca** [duckduckgo/zeroclickinfo-spice#3511]
What happened to the movies instant answer?

Now any movie related query I do doesn't return an instant answer anymore, any reason for that or am I'm missing something?

Even testing the example ones doesn't trigger anything.

------
IA Page:  http://duck.co/ia/view/movies_filmography 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @whalenrp

**Comment by moollaza** [comment]
@danielfranca thanks for mentioning this. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

It looks like the filmography IA was disabled by our automated system. Likely due to an external API issue. Seeing as we're in maintenance mode I don't expect this IA to be re-enabled until further notice.

This will be marked as tolerated and closed.
