### ISSUE TITLE
DOTA 2 Heroes: Doesn't activate anymore

### ISSUE THREAD

**Issue by cafehaine** [duckduckgo/zeroclickinfo-spice#3569]
The app doesn't seem to work anymore, the examples queries don't activate the app (like `dota2 blink`)

------
IA Page:  http://duck.co/ia/view/dota2 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @echosa

**Comment by echosa** [comment]
I think this was removed from DDG around the time they cancelled the DuckDuckHack initiative. https://duckduckhack.com/

**Comment by moollaza** [comment]
@cafehaine thanks for the feedback! It looks like this IA is offline, which is why its not triggering.

I gave it a quick test and unfortunately it seems like there's now some design breakage so getting it back online would require some work. Seeing as DuckDuckHack is in maintenance mode I think this is likely going to stay offline. Marking this issue as tolerated.
