### ISSUE TITLE
Airlines: Sometimes not display info

### ISSUE THREAD

**Issue by borisov87** [duckduckgo/zeroclickinfo-spice#3590]
Yesterday user post info in reddit for problem

https://www.reddit.com/r/duckduckgo/comments/bew7tf/could_ddg_add_flight_status_in_search_results/

When I try yesterday all be OK, now again not display info. 
https://duckduckgo.com/?q=flight+ai136&t=canonical&ia=flights

Flight is scheduled as google say
![Screenshot_2019-04-20 flight ai136 - Google Search](https://user-images.githubusercontent.com/5180111/56454773-7f941e80-635e-11e9-9027-615ff03ccbce.png)

BTW now i see in url `ia=images` instead `ia=flights` but even when force to be flights not work
https://duckduckgo.com/?q=flight+ai136&t=canonical&ia=images 

------
IA Page:  http://duck.co/ia/view/airlines 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @amoraleda

**Comment by amoraleda** [comment]
@borisov87 thanks for posting this issue. As far as I know, Duck Duck Go is in maintenance mode until further notice. You can see a similar issue closed by this reason here: https://github.com/duckduckgo/zeroclickinfo-spice/issues/3522

Thanks! =)

**Comment by moollaza** [comment]
@borisov87 thanks for reporting. This is the expected behaviour of the Instant Answer depending on the type of query.

When the query is for a specific flight, the Instant Answers searches for arrivals from 6 hours ago until 6 hours from now. So in the above case if that flights isn't set to land during that time it won't show an answer.

However, if you search for flights between two cities/airport codes, and specify the airline, it will show the status of any flights from 6 hours ago until 6 hours into the future, whether they're set to arrive or depart.

Searching `air india delhi to madrid` will show you the result you're expecting to see when you search `ai 136`.

I understand this might not match Google's results and could definitely be improved, but as @amoraleda pointed out, DuckDuckHack is currently in maintenance mode so only bug reports for crucial fixes are being accepted currently.

Seeing as the Instant Answer is technically working, I will mark this as tolerated and close the issue.
