### ISSUE TITLE
Thesaurus missing major meaning

### ISSUE THREAD

**Issue by yegg** [duckduckgo/zeroclickinfo-spice#412]
https://duckduckgo.com/?q=thesaurus+friendly

vs

http://words.bighugelabs.com/friendly

**Comment by Jedidiah** [comment]
Would something along these lines work better?

![screen shot 2015-01-11 at 23 48 00](https://cloud.githubusercontent.com/assets/113929/5697599/322c519c-99ed-11e4-8eba-4b0b2002c3b3.png)

**Comment by javathunderman** [comment]
@moollaza Any update on this?

**Comment by moollaza** [comment]
@Jedidiah apologies for the late reply, I hadn't noticed your comment. That approach certainly looks like a step in the right direction!

It seems like there's actually a bug here though because the Thesaurus IA is giving different results for the two queries: https://duckduckgo.com/?q=similar+to+friendly&ia=thesaurus and https://duckduckgo.com/?q=thesaurus+friendly

**Comment by Jedidiah** [comment]
I think it's probably happening because we're setting different modes for the two queries https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/thesaurus/thesaurus.js#L24-L25

Similar to is set to `sim` and Thesaurus `syn`. I was thinking thesaurus should really show all modes.

**Comment by moollaza** [comment]
>I was thinking thesaurus should really show all modes.

@Jedidiah looking at your example, I agree I think that approach would work well.

I don't like copying Google/Bing/etc but it seems like most of them also so antonyms and other meanings when searching for synonyms or thesaurus

**Comment by sekhavati** [comment]
I'd be happy to take a look at this if nobody else already is?
