### ISSUE TITLE
Convert Last.fm to the new Spice APIs

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#684]
Most of the Last.fm instant answers are broken:

Top Tracks:
![screen shot 2014-05-06 at 10 06 20 am](https://cloud.githubusercontent.com/assets/81969/2890275/bea05032-d527-11e3-9d3c-6ad7b2a1d106.png)

Albums:
![screen shot 2014-05-06 at 10 06 29 am](https://cloud.githubusercontent.com/assets/81969/2890280/c5c748e8-d527-11e3-8608-0a3833442250.png)

But artist search has been ported:
![screen shot 2014-05-06 at 10 06 38 am](https://cloud.githubusercontent.com/assets/81969/2890284/cec951fc-d527-11e3-9991-47e758dacf19.png)

------ 

IA Page: https://duck.co/ia/view/lastfm_artist

**Comment by javathunderman** [comment]
@jagtalon Curious- what do we have to do here? Looks like it's already been ported...

**Comment by moollaza** [comment]
@javathunderman the TopTracks and Albums Spices haven't been updated yet, the code is partially updated, but the Spice API underwent further improvements and the IA's need to match the newest API so that they display results properly (if you take a peek at those screenshots, the results are broken in DuckPAN)

**Comment by moollaza** [comment]
- https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/lastfm/song/lastfm_song.js
- https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/lastfm/top_tracks/lastfm_top_tracks.js

**Comment by javathunderman** [comment]
@moollaza Ok, just wondering...
