### ISSUE TITLE
MassOnTime: Convert to use a map

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#708]
It currently looks like this:
![screen shot 2014-05-09 at 11 15 19 am](https://cloud.githubusercontent.com/assets/81969/2929724/c1cab524-d78c-11e3-9914-1d6ce12de838.png)

It would be better as a map. Check out https://duck.co/duckduckhack/spice_displaying#models for docs about that

https://duck.co/ia/view/mass_on_time

**Comment by jagtalon** [comment]
@laouji I see what you mean. Yeah it looks like there's overlap with Yelp with "catholic churches", but it seems to be good with "catholic adoration". I'm not really sure either. CC @abeyang @moollaza what do you think?

**Comment by abeyang** [comment]
@jagtalon how hard would it be to hide the images, and maybe move the number badge to the right, and change the backing color? Can mock something up if you want, but just want to see what's possible.

@chrismorast any thoughts on this one?

**Comment by moollaza** [comment]
@jagtalon @abeyang we have a plan to generalize the Places view to allow for custom templates but that's a few weeks away.

In the intrim, could we move forward with the design as is? Having the map makes this kind of IA considerably better and more informative. One thought for the lack of images would be to use icons that represent something, like the church type, for example.

**Comment by moollaza** [comment]
Regarding the Yelp overlap, I'm actually see much better results from this IA compared to Yelp. MassOnTime gives churches from my town and neighbouring ones that are quite close. The yelp results are more focused on Toronto, which is about 40 mins from where I'm located.

**Comment by jagtalon** [comment]
@moollaza I agree with that. @laouji where can we find your code? Can you make a PR?

**Comment by laouji** [comment]
Hey sorry for the slow response. I just made a pull request.

I guess my main concern with using the maps is that the original author of this Spice spent time making different templates for when the result was a Parish and when the result is an Event.
I think for the most part the results deliver addresses to churches, but sometimes the result is a special event that it only available for a limited time.

I tried passing the time of the event to the template the same way you demonstrate in your documentation (https://duck.co/duckduckhack/spice_displaying#model), but it doesn't seem to display anywhere on the information tile:

```javascript
results.hours = { 
    Sun: startime_12h + ' - ' + endtime_12h 
};
```

And actually this is not good because there's no guarantee that the event is on a Sunday... I'd have to do some crazy parsing of the date to figure out what day of the week it is because the Mass on Time API returns start and end time strings like this '2015-01-25T11:00:19Z'.

I think the start and end dates of the event are quite important, but I'm not really sure how to include them using the Maps template.


As for the icons, I'm unfortunately not a graphic designer so I doubt I could make anything half decent icon-wise. But if anyone is willing to make them, using the 'eventtypeid' to switch between different icons would be one way to do it.

The types as defined by the original author are:
```
        1 : "Adoration",
        2 : "Confession",
        3 : "Devotion",
        5 : "Holy Day Mass",
        6 : "Holy Day Mass (Vigil)",
        7 : "Weekday Mass",
        8 : "Weekend Mass",
        9 : "Service"
```

**Comment by abeyang** [comment]
@laouji sorry, I don't have access to the returned API results. Can you throw the complete returned result onto a gist somewhere and share it with us? Want to see what exactly is being returned -- thanks!

**Comment by laouji** [comment]
@abeyang OK, here's a gist for you:
https://gist.github.com/laouji/387ea59b2673c528e072

**Comment by jagtalon** [comment]
@laouji weird--some places don't even have the eventtypeid or the starttime like the places around me (https://duckduckgo.com/js/spice/mass_on_time/parish/malvern%2C%20pennsylvania%2C%20united%20states/current). Would you know about this inconsistency? Might be a bug on their end.

**Comment by laouji** [comment]
I'm not sure why the api is like that but the code is set to default to the label 'Service' if there is no event type id.

I guess it depends on the completeness of their data.

**Comment by moollaza** [comment]
This uses a map now...
